Parser/Functions/RichPresenceDisplayFunction.cs, Parser/Internal/ExpressionTokenizer.cs, Parser/Internal/InterpreterScope.cs, Properties/AssemblyInfo.cs, Tests/Parser/Internal/ExpressionGroupTests.cs, Tests/Parser/LocalAchievementsTests.cs, Views/AboutDialog.xaml.cs, Views/MainWindow.xaml.cs
=> Remove unnecessary using statements

Parser/Functions/PrevFunction.cs, Parser/Internal/FunctionDefinitionExpression.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
=> extract mathematic modifiers from prev accessor clause

ViewModels/GameViewModel.cs, ViewModels/GeneratedAchievementViewModel.cs
prevents IDs from changing when refreshing from disk in emulator
=> generate local achievement IDs

Data/Requirement.cs, Parser/AchievementBuilder.cs, Parser/Functions/ComparisonModificationFunction.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Functions/OnceFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, ViewModels/RequirementComparisonViewModel.cs, ViewModels/RequirementViewModel.cs
via `once()`, `repeated()`, `never()` and `unless()`
for example:
```once(byte(0x1234) == 1 && byte(0x2345) == 2)```
would generate:
```
AndNext 8-bit memory 0x1234 == 1
8-bit memory 0x2345 == 2 (1)
```
and
```never(byte(0x1234) == 1 && byte(0x2345) == 2)```
would generate:
```
AndNext 8-bit memory 0x1234 == 1
ResetIf 8-bit memory 0x2345 == 2
```
=> support for AndNext

Parser/LocalAchievements.cs, Properties/app.manifest, RATools.csproj, ViewModels/MainWindowViewModel.cs, ViewModels/NewScriptDialogViewModel.cs, ViewModels/RichPresenceViewModel.cs, Views/MainWindow.xaml.cs
=>  replace MessageBoxViewModel calls with TaskDialogViewModel calls

ViewModels/MainWindowViewModel.cs, Views/MainWindow.xaml
implements #75 
depends on https://github.com/Jamiras/Core/pull/11
=> add support for opening files via drag/drop

ViewModels/ScriptViewModel.cs
implements #50 
depends on https://github.com/Jamiras/Core/pull/10
=> newline at end of content should add blank line to editor

Parser/AchievementBuilder.cs, Parser/TriggerBuilderContext.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs
=> merge multiple operations into a single term in value expression

Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
=> don't invert clause containing AndNext

Services/Settings.cs, ViewModels/MainWindowViewModel.cs
=> force read/write of ini and write of log to application directory

Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
=> allow AddAddress in subtraction

Parser/LocalAchievements.cs
=> increase maximum serialized achievement length to 64KB

Data/RequirementEx.cs, Parser/AchievementBuilder.cs, RATools.csproj, ViewModels/RequirementComparisonViewModel.cs, ViewModels/RequirementGroupViewModel.cs
=> improve requirement matching to account for combining requirements

Data/Requirement.cs, Parser/AchievementBuilder.cs, Parser/AchievementScriptInterpreter.cs, Parser/Functions/MeasuredFunction.cs, Parser/ScriptInterpreterAchievementBuilder.cs, RATools.csproj, Tests/Data/RequirementTests.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/MeasuredFunctionTests.cs, Tests/RATools.Tests.csproj
Support for MeasuredIf.
`measured(byte(0x1234) == 10, when=byte(0x2345) == 7)`
would become:
```
Measured   8-bit Mem 0x1234 == 10
MeasuredIf 8-bit Mem 0x2345 == 7
```
=> add when parameter to measured function

Parser/Functions/FlagConditionFunction.cs
Fixes #163 
When expanding `never(A || B || C)` to `never(A) && never(B) && never(C)`, it was doing so recursively, for example, with a middle step of `never(A || B) && never(C)`. If the chain was long enough, a "maximum recursion depth" error would occur. 
This is not only problematic, but also inefficient, as the `never` function has to be looked up at each level. I've updated the logic to capture all the individual OR clauses and rejoin them with AND clauses without using recursion.
=> expand multi-condition modifier function without recursive scoping

Parser/Functions/FlagConditionFunction.cs, Tests/Parser/Functions/FlagConditionFunctionTests.cs, Tests/RATools.Tests.csproj
=> fix error message for attempting to change flag on condition

Data/Field.cs, Parser/AchievementBuilder.cs, Parser/AchievementScriptInterpreter.cs, Tests/Data/FieldTests.cs, Tests/Parser/AchievementBuilderTests.cs, ViewModels/NewScriptDialogViewModel.cs
=> add bcd() function

Parser/AchievementBuilder.cs, Parser/Functions/ComparisonModificationFunction.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
=> better support for OrNext in CollapseForSubClause

Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
=> invert merging logic when creating union of ResetIf conditions

Parser/TriggerBuilderContext.cs, Tests/Parser/TriggerBuilderContextTests.cs, Tests/RATools.Tests.csproj
=> distribute multiplication/division over terms in value expression

Parser/Internal/InterpreterScope.cs
Minor performance improvement. 
Avoids allocating dictionaries for variable and function definitions in every scope and only does it when the scope has variable or function definitions.
=> only initialize dictionaries when necessary

Services/ISettings.cs, Services/RAWebCache.cs, Services/Settings.cs, ViewModels/GameStatsViewModel.cs, ViewModels/MainWindowViewModel.cs, ViewModels/OpenTicketsViewModel.cs
* `ticketmanager` now requires a cookie, provide via ini file
* `/game/` and `/achievement/` links are now lowercase
* use https for all URLs
* masters list in game page is now in a tab
=> fix analysis pages for website changes

Data/Requirement.cs, Data/RequirementEx.cs, Parser/AchievementBuilder.cs, Parser/Functions/RepeatedFunction.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
For example:
```
repeated(2, byte(0x1234) == 1 && never(byte(0x2345) == 2)))
```
becomes
```
ResetNextIf 8-bit 0x2345 = 2
8-bit 0x1234 = 1 (2)
```
=> generate ResetNextIf from never() clause inside repeated()

Parser/Internal/ComparisonExpression.cs, Parser/Internal/MathematicExpression.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/ComparisonExpressionTests.cs
=> invert condition when constant is on left

Parser/Internal/FunctionDefinitionExpression.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/FunctionDefinitionExpressionTests.cs
=> allow functions to have default parameters

Parser/ScriptInterpreterAchievementBuilder.cs
closes #243 
Modifies condition chain processing to only recurse down the left side of the expression tree as the parser tends to generate right-heavy trees.
This prevents the crash in #243, but does not address the issue that the generated achievement will be too large to upload to the server.
=> evaluate conditional chain with minimal recursion

Parser/AchievementBuilder.cs, Parser/TriggerBuilderContext.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs, Tests/Parser/TriggerBuilderContextTests.cs
Fixes an issue where adding pointed-at values was generating multiple Measured conditions instead of an AddSource sequence. Also adds support for SubSource and multiplication when using Measured values.
=> support for more complex value strings

ViewModels/MainWindowViewModel.cs
closes #225 
Makes the "Could not find game ID" warning non-terminal. The attempt to locate code notes will be skipped, and the behavior will be the same as if code notes could not be found (Update Local is disabled)
=> allow loading file without a game id

Parser/Internal/ExpressionGroupCollection.cs
When pasting a line that starts with "&&", "+", or any other non-identifier at the top-level of script, the line would be marked as invalid as the line before the pasted line was not being examined.
Also occurred when expanding a function definition by duplicating it and changing the "function f() =>" to a combining character.
=> process preceding lines when pasting text starting with a combining character

ViewModels/TriggerComparisonViewModel.cs
fixes an issue where #281 was causing the Core group to not match with itself.
=> only require exact matching for alt groups

ViewModels/AchievementViewModel.cs, ViewModels/NewScriptDialogViewModel.cs
closes #195 
If an XXXX-Local.txt file is found, anything defined in the file will be available in the New Script dialog. They will be unselected by default.
=> support for dumping local acheivements

Source/Parser/AchievementBuilder.cs, Source/Parser/Functions/RepeatedFunction.cs, Source/Parser/Internal/ConditionalExpression.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, Tests/Parser/Functions/TallyFunctionTests.cs
Prevents "Modifier not allowed in subclause" error if repeated has more than two nevers
https://discord.com/channels/310192285306454017/936655398725902356/970872775336157204
=> fix repeated with multiple nevers

Source/Parser/Functions/MeasuredFunction.cs, Source/Parser/Internal/ExpressionGroupCollection.cs, Source/Parser/Internal/FunctionCallExpression.cs, Source/Parser/Internal/ParseErrorExpression.cs, Source/Parser/Internal/VariableExpression.cs, Source/Parser/TriggerBuilderContext.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/971232785371123792
=> fix error when non-hitcount measured value has a reset for a pause/resetnextif

Source/Parser/Internal/IfExpression.cs, Tests/Parser/Internal/IfExpressionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/967125329137266768
=> expect whitespace after else keyword

Source/Services/RAWebCache.cs, Source/ViewModels/MasteryViewModel.cs
also fixes mastery stats for games with age gate confirmation
=> separate per-user mastery dump information from general mastery dump information

Source/Data/RichPresence.cs, Source/Parser/LocalAssets.cs, Source/Parser/RichPresenceBuilder.cs, Source/ViewModels/AssetViewModelBase.cs, Source/ViewModels/GameViewModel.cs, Source/ViewModels/RequirementComparisonViewModel.cs, Source/ViewModels/RequirementGroupViewModel.cs, Source/ViewModels/RequirementViewModel.cs, Source/ViewModels/RichPresenceViewModel.cs, Source/ViewModels/TriggerComparisonViewModel.cs, Source/ViewModels/TriggerViewModel.cs, Source/ViewModels/UpdateLocalViewModel.cs, Source/Views/AssetViewer.xaml, Source/Views/RichPresenceViewer.xaml
Makes Rich Presence show up in the Update Local dialog. Also updates the rich presence serialized limit warning to 64KB.
=> add RichPresence model

Source/Services/RAWebCache.cs, Source/ViewModels/ConditionsAnalyzerViewModel.cs, Source/ViewModels/GameDataSnapshotViewModel.cs, Source/ViewModels/GameStatsViewModel.cs, Source/ViewModels/MainWindowViewModel.cs, Source/ViewModels/MasteryViewModel.cs, Source/ViewModels/OpenTicketsViewModel.cs, Source/Views/GameStatsDialog.xaml
=> use web API for game stats and tickets analysis

Source/ViewModels/LeaderboardViewModel.cs
=> prevent null exception trying to find notes for local leaderboard when creating New Script

Source/Services/RAWebCache.cs, Source/ViewModels/GameStatsViewModel.cs, Source/ViewModels/MainWindowViewModel.cs, Source/ViewModels/MasteryViewModel.cs, Source/ViewModels/UserMasteriesViewModel.cs, Source/Views/MainWindow.xaml, Source/Views/MainWindow.xaml.cs, Source/Views/UserMasteriesDialog.xaml, Source/Views/UserMasteriesDialog.xaml.cs
separates out a compile-time option for the mastery dialog so it can be used generically at runtime.
=> add User Mastery dialog

Source/Parser/TriggerBuilderContext.cs, Tests/Parser/TriggerBuilderContextTests.cs
=> fix serialization of implicitly measured value with a non-integer scalar

Source/Services/RAWebCache.cs, Source/ViewModels/MainWindowViewModel.cs
also prevent requests if username is "RATools"
=> show error when server does not respond with JSON

Source/ViewModels/GameViewModel.cs
Replaces a direct reference to the previous editor with a key so the updated editor can be found when navigation back. Also allows the outdated editor to be free'd.
=> fix back navigation when asset changes

Source/Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/990783319010582580
=> don't convert bitcount=8 to byte=255 when wrapped in measured

Source/ViewModels/NewScriptDialogViewModel.cs
https://discord.com/channels/310192285306454017/936655398725902356/1008829359303446578
=> fix null reference dumping rich presence with measured value in display string

Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs
Improves "Multiplication by complex value not supported" error to state "Cannot multiply two values with differing pointers" or "Cannot multiply pointer value and modified value" as appropriate (also provides a different message for division).
=> Better error messages when multiplying or dividing with pointer chains

Source/Parser/Expressions/BooleanConstantExpression.cs, Source/ViewModels/EditorViewModel.cs, Source/ViewModels/OptionsDialogViewModel.cs
floats were not assigned a highlight color and booleans were highlighting one character past their end
=> fix float/boolean highlighting

Source/ViewModels/GameViewModel.cs
https://discord.com/channels/310192285306454017/936655398725902356/1057315480861417552
=> prevent exception dumping game with no achievements or leaderboards

Source/Parser/AchievementBuilder.cs, Source/Parser/Expressions/BooleanConstantExpression.cs, Source/Parser/Expressions/ComparisonExpression.cs, Source/Parser/Expressions/FloatConstantExpression.cs, Source/Parser/Expressions/IntegerConstantExpression.cs, Source/Parser/Expressions/MathematicExpression.cs, Source/Parser/Expressions/StringConstantExpression.cs, Source/Parser/Expressions/Trigger/MemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/RequirementExpressionBase.cs, Source/Parser/Internal/ICompararisonNormalizeExpression.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Expressions/ExpressionTests.cs, Tests/Parser/Expressions/Trigger/BehavioralRequirementExpression_Tests.cs, Tests/Parser/Expressions/Trigger/MemoryValueExpressionTests.cs
additionally supports merging bits nested under pointers
=> move BitCount merging into MemoryValueExpression

Source/ViewModels/GameViewModel.cs, Source/ViewModels/NewScriptDialogViewModel.cs
=> prevent exception dumping script for game with incomplete leaderboards

Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Source/ViewModels/NewScriptDialogViewModel.cs, Tests/Parser/Expressions/Trigger/RequirementClauseExpression_Tests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1070002110923538463
=> don't optimize alts if it would generate nested clauses

Source/Parser/Expressions/Trigger/DisableWhenExpression.cs, Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Source/Parser/Expressions/Trigger/TalliedRequirementExpression.cs, Source/Parser/Functions/RepeatedFunction.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
=> don't create multiple reset clauses for single repeated function

Source/Parser/AchievementBuilder.cs, Tests/Parser/ValueBuilderContextTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1070794620054798336
=> prevent exception processing tallied value comparing against negative value

Source/ViewModels/NewScriptDialogViewModel.cs
https://discord.com/channels/310192285306454017/533411674162593812/1071605486757093446
=> fix empty notes list when no assets present

Source/Parser/Expressions/Trigger/FieldFactory.cs, Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1097991697335599175
=> fix infinite loop when underflow adjustment exceeds MAX_INT

Source/ViewModels/AchievementViewModel.cs
https://discord.com/channels/310192285306454017/936655398725902356/1100168206657798284
=> fix measured target calculation for tally

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1105265255661187163
=> don't share AddAddress if value is modified

Source/Parser/Expressions/ComparisonExpression.cs, Source/Parser/Internal/InterpreterScope.cs, Source/ViewModels/GameViewModel.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Expressions/ComparisonExpressionTests.cs, Tests/Parser/Functions/AchievementFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1113995364081614858
=> prevent infinite recursion passing function to function using variable with same name

Source/Parser/AchievementBuilder.cs, Source/Parser/Expressions/Trigger/BehavioralRequirementExpression.cs, Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Source/Parser/RequirementMerger.cs, Source/Parser/TriggerBuilderContext.cs, Source/ViewModels/NewScriptDialogViewModel.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Expressions/Trigger/BehavioralRequirementExpression_Tests.cs, Tests/Parser/Functions/OnceFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, Tests/Parser/RequirementMergerTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1180402821309399120
Also allow automatically split `trigger_when(measured(...))` into `trigger_when(always_false())` and `measured(...)` alt groups.
=> allow trigger_when(always_false()) in alt groups

Source/Parser/Expressions/FunctionCallExpression.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Functions/FormatFunction.cs, Source/Parser/Functions/LeaderboardFunction.cs, Source/Parser/Functions/TallyFunction.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1184263999685148843
=> allow max_of to be called with an array

Source/Parser/RequirementMerger.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Expressions/ConditionalExpressionTests.cs, Tests/Parser/RequirementMergerTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1187200525414961253
=> don't collapse comprehensive mutually exclusive alts into an always_true

.gitignore, RATools.sln, Source/Data/Achievement.cs, Source/Data/AssetBase.cs, Source/Data/CodeNote.cs, Source/Data/Field.cs, Source/Data/RATools.Data.csproj, Source/Data/Requirement.cs, Source/Data/RequirementEx.cs, Source/Data/RequirementGroup.cs, Source/Data/RichPresence.cs, Source/Data/Trigger.cs, Source/Data/Value.cs, Source/Parser/AchievementBuilder.cs, Source/Parser/Functions/AlwaysFalseFunction.cs, Source/Parser/Functions/AlwaysTrueFunction.cs, Source/Parser/LocalAssets.cs, Source/RATools.csproj, Source/RATools.properties, Source/ViewModels/TriggerViewModel.cs, Tests/Data/FieldTests.cs, Tests/Data/RATools.Data.Tests.csproj, Tests/Data/RequirementExTests.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/RATools.Tests.csproj
First step for disentangling the UI from the parser for a potential non-UI command line processor.
=> split RATools.Data into separate DLL

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Tests/Parser/Expressions/Trigger/MemoryValueExpressionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1190481156781641789
=> don't collapse inverted bits into bitcount

Source/Parser/Expressions/DictionaryExpression.cs, Tests/Parser/Expressions/DictionaryExpressionTests.cs
https://discord.com/channels/310192285306454017/533411674162593812/1201985764091494460
=> improve error message when using complex objects as dictionary key

Source/Parser/Functions/MemoryAccessorFunction.cs, Tests/Parser/Expressions/Trigger/MemoryAcessorExpressionTests.cs
https://discord.com/channels/310192285306454017/533411674162593812/1200218636791595110
=> fix pointer offset calculation when subtracting

Source/Parser/LocalAssets.cs, Source/ViewModels/GameViewModel.cs, Source/ViewModels/MainWindowViewModel.cs, Source/Views/GameViewer.xaml
=> add tooltip for local file path to local footer text

Source/Parser/Expressions/IndexedVariableExpression.cs, Source/Parser/Expressions/VariableExpression.cs, Tests/Parser/Functions/ArrayMapFunctionTests.cs, Tests/Parser/Functions/ArrayPopFunctionTests.cs, Tests/Parser/Functions/ArrayPushFunctionTests.cs, Tests/Parser/Functions/FunctionTests.cs
=> when retrieving a nested array/dictionary from a by-reference dictionary, return it by-reference

Source/Data/Field.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs
=> honor endianness when shrinking read size

Source/ViewModels/RequirementViewModel.cs, Tests/Parser/Expressions/ExpressionBaseTests.cs, Tests/ViewModels/RequirementViewModelTests.cs
=> don't collapse constant comparisons at end of AddSource chain into always_true/always_false when displaying

Source/Data/RequirementEx.cs, Source/Parser/ScriptBuilderContext.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/RequirementsOptimizerTests.cs, Tests/Parser/Internal/ScriptBuilderContextTests.cs
=> don't eliminate always_true clause at end of AddSource chain

Source/Parser/Expressions/MathematicExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1227771952811212810
=> report error trying to combine arithmetic and bitwise operations

Source/Data/Value.cs, Source/Parser/Expressions/Trigger/MeasuredRequirementExpression.cs, Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/Parser/ValueBuilder.cs, Source/ViewModels/LeaderboardViewModel.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs, Tests/Parser/Functions/TallyFunctionTests.cs, Tests/Parser/ValueBuilderTests.cs
=> don't remove trailing +0 in tallied value

Source/Parser/ScriptBuilderContext.cs, Tests/Parser/Internal/ScriptBuilderContextTests.cs
https://discord.com/channels/310192285306454017/533411674162593812/1230177146958385275
=> don't wrap measured value with AddHits chain in "tally(0,"

Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Expressions/LeftRightExpressionBase.cs, Source/Parser/Expressions/MathematicExpression.cs, Source/Parser/Functions/SumOfFunction.cs, Tests/Parser/Functions/AchievementFunctionTests.cs, Tests/Parser/Functions/SumOfFunctionTests.cs
Error message is now "Cannot convert mathematic expression to requirement" instead of "Cannot add mathematic expression and mathematic expression".
https://discord.com/channels/310192285306454017/936655398725902356/1236888324799729696
=> better error when summing expressions that cannot be converted to requirements

Source/Parser/Functions/PrevPriorFunction.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/PrevPriorFunctionTests.cs
=> distribute prev across requirement condition

Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
=> fix error optimizing clause containing only always true/false expressions

Source/Parser/Expressions/AssignmentExpression.cs, Source/Parser/Expressions/FunctionCallExpression.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Tests/Parser/Expressions/FunctionDefinitionExpressionTests.cs
=> allow lambda functions in default parameters

Source/Parser/PublishedAssets.cs, Source/ViewModels/GameViewModel.cs, Source/rascript-cli/RAScriptCLI.cs, Tests/Regression/ScriptTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1241955588796321802
Also adds logic to merge with existing published achievements.
=> Generate IDs for local achievements when using CLI

Source/Parser/ScriptBuilderContext.cs, Source/rascript-cli/RAScriptCLI.cs, Tests/Parser/Internal/ScriptBuilderContextTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1250523195283345529
=> Fix dumping script with multiple clauses containing both AddSource and SubSource

Source/Parser/Expressions/FunctionCallExpression.cs
fixes #495 
Now that RATools supports calling a function returned by another function, it saw `word(0x0000)(byte(0x0000) == 10)` as valid syntax, but `word(0x0000)` failed to return a function that would be passed `byte(0x0000) == 10`. When trying to report the error and underline the problematic code, it was looking for a function name, which doesn't exist when chaining.
=> prevent exception when it looks like a function chains into another

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/FunctionCallExpression.cs, Source/Parser/Functions/AssertFunction.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/AssertFunctionTests.cs, Tests/Parser/Functions/FunctionTests.cs
closes #492
Optional second parameter allows custom error messages:
=> add assert function

Source/Views/MainWindow.xaml.cs
=> open script passed as parameter

Source/Parser/Functions/MaxOfFunction.cs, Source/ViewModels/TriggerViewModel.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1283599611063304285
=> prevent exception when max_of() has no parameters

Source/Parser/Expressions/Trigger/MaxOfRequirementExpression.cs, Source/Parser/Functions/LeaderboardFunction.cs, Source/Parser/Functions/RichPresenceConditionalDisplayFunction.cs, Source/Parser/Functions/RichPresenceDisplayFunction.cs, Source/Parser/TriggerBuilder.cs, Source/Parser/ValueBuilder.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs
https://discord.com/channels/310192285306454017/310195377993416714/1284879961911726187
=> Pass MinimumVersion into sub-triggers for leaderboards and rich presence

Source/Parser/Expressions/FunctionCallExpression.cs, Source/Parser/InterpreterScope.cs, Tests/Parser/Expressions/DictionaryExpressionTests.cs
=> Fix exception calling global function from within function invoked via dictionary reference

Source/Parser/Expressions/Trigger/MemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/RequirementConditionExpression.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
=> don't discard duplicated masks on both sides of comparison

Source/Parser/Expressions/Trigger/MeasuredRequirementExpression.cs, Source/Parser/Expressions/Trigger/MemoryAccessorExpressionBase.cs, Tests/Parser/Functions/MeasuredFunctionTests.cs
https://discord.com/channels/310192285306454017/962817919698501702/1279868548235133021
=> allow measured(constant) for value expressions

Source/Views/GameViewer.xaml
=> add type indicators to achievement list

Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Source/Parser/Functions/AnyOfFunction.cs, Tests/Parser/Functions/AnyOfFunctionTests.cs
https://discord.com/channels/310192285306454017/1285315597843955773/1287936368554545216
=> prevent minimum version from collapsing ors with complex conditions

Source/Data/Field.cs, Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/Trigger/FieldFactory.cs, Source/Parser/Functions/AsciiStringEqualsFunction.cs, Source/Parser/Functions/RichPresenceAsciiStringLookupFunction.cs, Source/Parser/RichPresenceBuilder.cs, Tests/Parser/Functions/RichPresenceAsciiStringLookupFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1287776829599518741
Takes an dictionary of string=>string values and determines a way to uniquely identify every item in the dictionary assuming the keys are ASCII strings. Then it generates a lookup using the mapped values.
=> add rich_presence_ascii_string_lookup function

Source/Parser/Expressions/ExpressionBase.cs, Tests/Parser/Expressions/ExpressionBaseTests.cs, Tests/Parser/Expressions/MathematicExpressionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1288619568159264850
=> support for unary minus

Source/Data/RichPresence.cs
https://discord.com/channels/310192285306454017/936655398725902356/1296184097609089134
=> prevent diff warning caused by trailing whitespace

Source/Data/RequirementOperator.cs, Source/Parser/Expressions/ExpressionBase.cs, Source/Parser/Expressions/MathematicExpression.cs, Source/Parser/Expressions/MathematicOperation.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1325229018697695345
Instead of erroring out when trying to combine multiple modified memrefs, attempt to store one in the recall variable.
=> allow ModifiedMemoryReferenceExpression to use Remember/Recall

Source/Data/Version.cs, Source/Parser/Expressions/Trigger/BehavioralRequirementExpression.cs, Tests/Parser/Expressions/Trigger/BehavioralRequirementExpression_Tests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1305112336838692894
=> optimization: remove hit target on never(once(...))

Source/Parser/Internal/RequirementsOptimizer.cs, Source/Parser/ScriptBuilderContext.cs, Tests/Parser/Internal/RequirementsOptimizerTests.cs, Tests/Parser/Internal/ScriptBuilderContextTests.cs
https://discord.com/channels/310192285306454017/1285315597843955773/1335380853009813565
https://discord.com/channels/310192285306454017/936655398725902356/1337899171042033735
=> don't eliminate ResetNextIf attached to PauseLock when it matches an outer ResetIf

Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs, Tests/Parser/Functions/MeasuredFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1352024349737222278
=> maintain CombiningOperator when using Remember/Recall

Source/Parser/Expressions/Trigger/RequirementConditionExpression.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
fixes https://discord.com/channels/310192285306454017/936655398725902356/1372891527348617259
converts the dynamic memory read to an AddSource and compares the result of that to the static memory read
=> fix comparing dynamic memory to static memory

Source/Parser/Functions/PrevPriorFunction.cs, Tests/Parser/Functions/PrevPriorFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1382399277258772791
=> distribute prev() across multiple conditions

Source/Data/Requirement.cs, Tests/Data/RequirementTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1394361513426555000
=> fix deserialization failure for modulus

Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Tests/Parser/Expressions/Trigger/RequirementClauseExpressionTests.cs
fixes https://discord.com/channels/310192285306454017/936655398725902356/1395634079151423538
=> don't split trigger_when(__ornext(...))

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Tests/Parser/Expressions/Trigger/MemoryValueExpressionTests.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs, Tests/Parser/ValueBuilderTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1402332064153600073
Use remember/recall to do addition first, and divide the total.
=> Don't decompose integer division of add chain

Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Expressions/ComparisonExpressionTests.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs, Tests/Parser/Functions/PrevPriorFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1403784074434187464
=> don't transit integer division for equality comparisons

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs
https://discord.com/channels/310192285306454017/533411674162593812/1354529281237188689
=> allow bitwise operations using remember/recall

Source/Parser/Expressions/IndexedVariableExpression.cs, Tests/Parser/Expressions/ClassMemberReferenceExpressionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1420276571494678570
=> Allow indexing of class member fields
