RATools.csproj
Fixes #15.
`Core` can keep targeting 3.5 safely.
=> Target .NET Framework 4.0

Parser/AchievementBuilder.cs, Properties/AssemblyInfo.cs, Tests/Parser/AchievementBuilderTests.cs, changelog.txt
Prevents an issue where a clause within a multi-clause condition would conflict with another clause outside the multi-clause condition, eliminating both.
=> Ignore multi-clause conditions when optimizing

Views/GameViewer.xaml, Views/MainWindow.xaml
The upgrade to .NET 4.0 had some unintended side effects to the UI. The modified marker gained a box, the icons lost their anti-aliasing, and the spacing between items increased.
old UI:
after upgrading to .NET 4.0:
with these changes:
=> Adjust UI for upgrade to .NET 4.0

ViewModels/GeneratedAchievementViewModel.cs, ViewModels/MainWindowViewModel.cs, ViewModels/RichPresenceViewModel.cs
The local directory is found by locating the `XXX-Notes.json` file. If the "Could not locate notes file" messagebox is shown, the "Update Local" right-click options will be disabled, and attempting to use the menu option or the shortcut key will show an error message.
=> disable Update Local if local directory is not known

Parser/LocalAchievements.cs, ViewModels/GeneratedAchievementViewModel.cs
If an `achievement()` call specifies an `id`, that will now be carried along with the generated achievement definition, both internally and when written to the local XXX-User.txt file. This allows the toolkit to merge the achievement generated by the `achievement()` call into an already published achievement, and improves support for modifying published achievements within the editor.
Additionally, it prevents unintentional duplication when both the title and description of a published achievement are modified by the `achievement()` call. Without the ID, title, or description to link the published achievement to the generated one, a new achievement was being added to the list.
=> support non-zero local achievement IDs (supports #29)

Parser/AchievementBuilder.cs, Parser/Functions/AlwaysFalseFunction.cs, Parser/Functions/AlwaysTrueFunction.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
also support comparisons where integer is on left by swapping the comparison order (i.e. `3>A` => `A<3`)
=> convert integer constant comparisons to always_true or always_false

Parser/AchievementBuilder.cs, Parser/AchievementScriptInterpreter.cs, Parser/Functions/AchievementFunction.cs, Parser/Internal/ExpressionGroup.cs, Parser/Internal/LeftRightExpressionBase.cs, Parser/Internal/MathematicExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/MathematicExpressionTests.cs, Tests/RATools.Tests.csproj, ViewModels/EditorViewModel.cs
fixes last issue reported in #51:
```
function score() => byte(0x8E) + byte(0x8F) * 100
achievement
(
title = "Nice Score", 
description = "Reach a score of 1234567 points",
points = 10,
trigger = score() >= 1234567
)
```
The code was incorrectly dividing 1234567 by 100 in an attempt to normalize the score() function, leading to a weird string of AddSources. However, with the "byte(0x8E)+" in there, it's not correct to divide both sides by 100. This situation is now detected, and reported as "Cannot normalize expression to eliminate multiplication".
=> better error message when attempting to multiply within a trigger clause

Parser/Functions/FlagConditionFunction.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
implements #53 
also converts `unless(A || B)` to `unless(A) && unless(B)`
=> convert never(A||B) to never(A)&&never(B)

Parser/AchievementScriptInterpreter.cs, Parser/Functions/BitFunction.cs, RATools.csproj, Tests/Parser/Functions/MemoryAccessFunctionTests.cs, Tests/RATools.Tests.csproj
supports indexing 32 bit values (index can be anything from 0-31), assuming 32-bit values are stored in little-endian order (which is consistent with `dword(address)` behavior).
indices 0-7 are bits from `address`, 8-15 are from `address+1`, 16-23 are from `address+2`, and 24-31 are from `address+3`
=> add 'bit(index, address)' function

Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
An achievement that only had OR clauses would generate an implicit always_true core group. When optimizing, a condition that appeared in all alt groups would be promoted to core. This change removes the always_true condition when a common condition is promoted.
=> remove always_true from core when promoting from alts

Parser/Internal/MathematicExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/MathematicExpressionTests.cs
* fixes subtraction of complex expressions (see #54)
* better handling of psuedo-implementation of abs:
`abs(A - B) <= 1` => `A + 1 - B <= 2`
Because the result is a unsigned int, the `+1` is required to prevent the -1 result from evaluating as higher than 1. The simplification code previously merged it into the 2, resulting in `A - B <= 1`, which won't handle the case where `B = A+1`. Now the subtraction of an unknown value is detected, along with the less than comparison, and the translation does not occur, leaving `A + 1 - B <= 2`
=> improve transitive math logic

Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
Updates the optimization code to uniformly treat AddSource/SubSource/AddHits chains as singular units.
This behavior has been cobbled into several of the optimization steps, and I ran into yet another place where it was desirable, so I modified the optimization routines to uniformly use an intermediate format that treats the chain as a single unit.
Also eliminates the "ambiguous logic clause" error (fixes #22). A core group is not required for optimization, but is still injected when serializing.
=> Treat chained conditions as a single unit when optimizing

ViewModels/GeneratedAchievementViewModel.cs, ViewModels/UpdateLocalViewModel.cs, Views/UpdateLocalDialog.xaml
Turns the "Update" and "Delete" column headers into hyperlinks. Clicking on them will "select all" if any items can be selected, or "deselect all" if all items are already selected.
=> select/deselect all for Update Local dialog

Parser/AchievementBuilder.cs, Parser/Internal/ComparisonExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Parser/TriggerBuilderContext.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/RegressionTests.cs
Implements #26 
Creates a cross-product of all of the eligible combinations when evaluating the conditions. The result is run through the existing optimizations to normalize any repetitive conditions.
`(A || B) && (A || C)`
=> `(A && A) || (A && C) || (B && A) || (B && C)`
=> `A || (A && C) || (B && A) || (B && C)`
Also supports more complex expressions and provides better support for not `!` operator on nested clauses. See test cases below for examples.
=> Support for multiple OR'd groups AND'ed together

Data/Field.cs, Parser/AchievementScriptInterpreter.cs, Parser/Functions/PrevPriorFunction.cs, RATools.csproj, Tests/Data/FieldTests.cs, ViewModels/NewScriptDialogViewModel.cs, ViewModels/RequirementViewModel.cs
Supports new "prior" data type in 0.76 integration DLL. Syntax is the same as `prev()`
=> add prior() function

RATools.csproj, Services/ISettings.cs, Services/Settings.cs, ViewModels/AboutDialogViewModel.cs, ViewModels/MainWindowViewModel.cs, ViewModels/NewScriptDialogViewModel.cs, ViewModels/OptionsDialogViewModel.cs, Views/AboutDialog.xaml, Views/MainWindow.xaml, Views/MainWindow.xaml.cs, Views/OptionsDialog.xaml, Views/OptionsDialog.xaml.cs
Implements #77 
The list of directories has been removed from the About dialog and is now present here, where it can be modified. It still shows a green check or red X to indicate whether or not the directory is valid.
Additionally, the paths no longer require `RACache\Data` (#76). The new ini field (without `RACache\Data`) is `EmulatorDirectories`. `RACacheDirectory` will be converted on load and replaced when saved.
=> add Settings dialog

.gitmodules, RATools.csproj, RATools.sln, README.md, Tests/RATools.Tests.csproj
Implements #16
I chose to write a batch file that uses powershell to download and extract the nUnit DLLs.
The `RATools + Core.sln` solution behaves as before, where it looks for the Core repository to be next to the RATools repository. The `RATools.sln` solution now expects to find the Core repository as a submodule and will build it (instead of relying on a pre-built DLL).
=> add Core as a submodule

Data/Requirement.cs, Parser/AchievementBuilder.cs, Parser/Functions/ComparisonModificationFunction.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Parser/TriggerBuilderContext.cs, Tests/Parser/AchievementBuilderTests.cs, ViewModels/NewScriptDialogViewModel.cs
fixes #68 
The basic problem was that `AchievementBuilder.ParseRequirements` wasn't handling the case where there was no core group correctly. Fixing that resulted in the dumper generating a trigger that said `1 == 1 &&`. Additional changes were made to convert that to `always_true() &&`. In the process, some duplicated code was merged.
=> fix generating achievement from string with no core group

Parser/Functions/RichPresenceLookupFunction.cs, Parser/RichPresenceBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
As specified in the Rich Presence docs: If a lookup doesn't contain a mapping
for a value, it will result in a blank (no space) value. You can change this
behavior by adding a single line to the lookup mapping '*' to the desired
fallback value.
Added support for that in RATools. The lookup map simply has to include a
"*" string constant key.
=> Support for fallback value in rich presence lookups

Parser/Functions/RichPresenceDisplayFunction.cs, Parser/Functions/RichPresenceLookupFunction.cs
1) Rich presence format parameters must be function calls. If anything else was
provided instead, a null object exception would bubble up to the user. An editor
error, "Invalid parameter, expected function call", is now reported to the user
instead.
2) In rich presence format strings, an empty placeholder resulted in a .net
exception bubbling up to the user. The tokenizer read an empty token inside the
brackets which was then passed onto Int32.Parse, causing the exception. There
are now 2 editor errors instead: if the brackets do not contain a number,
"Empty parameter index" is reported. Otherwise, if Int32.Parse fails,
"Invalid parameter index" is reported (can happen if the number is a float).
3) A minor bug that caused errors generated while processing a rich
presence lookup to not …
=> Some fixes to rich-presence-related error reporting

Parser/LocalAchievements.cs, Tests/Parser/LocalAchievementsTests.cs, Tests/Parser/RegressionTests.cs, ViewModels/GameViewModel.cs, ViewModels/GeneratedAchievementViewModel.cs, ViewModels/UpdateLocalViewModel.cs
fixes #49 
When updating multiple achievements, each modification to the file is done serially, so it behaves the same as if you just did an Update Local for each selected achievement individually.
The problem is that the validation is occuring each time the file is written, regardless of which particular achievement is being written, so once the "too large" item is there, it'll be reported for every update after that.
I've modified the logic to only validate the file once on multi-update and only validate the individual achievement on single-update.
=> only validate local achievements being updated

Data/Requirement.cs, Parser/AchievementBuilder.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
also normalize conditions so constants are on the right
adresses two bullet points from #32:
* remove duplicate conditions inc. when operands are swapped
* remove duplicate conditions with differing hit counts (prioritize the lower hit count condition?)
- higher hit count is correct - if A must be true for 3 frames and 5 frames, it must be true for 5 frames.
=> allow conditions with differing HitCounts to be merged

Parser/Internal/MathematicExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/MathematicExpressionTests.cs
For normalizing complex comparisons like:
* `(word(0x1234) - 1) * 4 < 100`   to   `word(0x1234) < 401` 
* `(word(0x1234) - 1) * 4 > (prev(word(0x1234)) - 1) * 4`   to   `word(0x001234) > prev(word(0x001234))`
=> improve logic for normalizing comparisons

Parser/Functions/AlwaysFalseFunction.cs, Parser/Functions/AlwaysTrueFunction.cs, Parser/Functions/BitFunction.cs, Parser/Functions/ComparisonModificationFunction.cs, Parser/Functions/FlagConditionFunction.cs, Parser/Functions/MemoryAccessorFunction.cs, Parser/Functions/OnceFunction.cs, Parser/Functions/PrevPriorFunction.cs, Parser/Functions/RangeFunction.cs, Parser/Functions/RepeatedFunction.cs, Parser/Functions/RichPresenceLookupFunction.cs, Parser/Functions/RichPresenceValueFunction.cs, Parser/Internal/ArrayExpression.cs, Parser/Internal/AssignmentExpression.cs, Parser/Internal/ComparisonExpression.cs, Parser/Internal/ConditionalExpression.cs, Parser/Internal/DictionaryExpression.cs, Parser/Internal/ExpressionBase.cs, Parser/Internal/IntegerConstantExpression.cs, Parser/Internal/MathematicExpression.cs, Parser/Internal/ReturnExpression.cs, Parser/Internal/StringConstantExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs
Fixes an issue where function parameters would sometimes not be highlighted if they were passed to an inner function. 
The syntax validation code was updating the location of the parameter each time it was passed to a lower function, thereby preventing the syntax highlighting code from finding it.
This was mostly an issue with constants as they were unmodified by the variable replacement code, allowing the location to be updated on the original expression. The solution is to always create a copy of the expression when calling `ReplaceVariables`, even if nothing is replaced.
I've also sprinkled a lot of `CopyLocation` calls on all of the copied expressions to ensure the location is correct if `ReplaceVariables` is called for something other than parameter expansion.
=> prevent modifying location of parameter data when evaluating parameters

Data/Field.cs, Parser/AchievementBuilder.cs, Parser/Functions/MemoryAccessorFunction.cs, Parser/Internal/MathematicExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
fixes #96 and #97
Replaces the accumulator with actual rebalancing and combining logic. 
Any time a memory read is subtracted on the left side of a comparison and the comparison is not "equal" or "not equal", a buffer value (maximum value of the memory read) is added to both sides of the equation to ensure the subtraction doesn't result in an underflow.
As such, the example in #96: `(count_a() > count_b() + 1)` becomes `(2 + bit1(0xabcd) + bit2(0xabcd) - bit4(0xabcd) - bit3(0xabcd)) > 3`, as does the equivalent `(count_a() - count_b() > 1)`. The third alternative from #97: `count_a() + 2 - count_b() > 3` also results in the same generated result.
There is an exception to this rule. If the user specifies their own adjustment for a "less than" condition: `byte(1) + 1 - byte(2) <= 2`, then …
=> account for possible underflow when transferring variables from one side of a condition to the other

Data/Field.cs, Data/Requirement.cs, Parser/AchievementBuilder.cs, Parser/Functions/ComparisonModificationFunction.cs, Parser/Functions/MemoryAccessorFunction.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Functions/MemoryAccessFunctionTests.cs
Allows memory accessors inside of memory accessors with a possible offset:
```
byte(word(0x1234))
bit6(dword(0x4567) + 10)
```
Indirect accessors on both sides of a condition must match, but allow for delta comparisons:
```
byte(word(0x1234) + 20) > prev(byte(word(0x1234) + 20))
```
=> add support for AddAddress

ViewModels/NewScriptDialogViewModel.cs
If a ticket's text contained a large line without a space, RATools
would fail to dump it and crash whilst trying to break it into smaller
lines. Happened with a URL to a proof image.
Also noticed that empty lines were not dumped correctly: the newline
would be missing and the following line would be double-commented:
```
//               //               next line
```
=> correctly dump tickets with empty and non-breakable lines

Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
Previous implementation relied on mathematically combining modifiers, which was sometimes avoided to prevent rounding errors. For comparisons (particularly comparing a value to its delta), the common modifiers can be eliminated instead of merged, so there's no reason to be concerned about the rounding errors.
=> simplify rebalancing comparisons by eliminating common modifiers

Parser/Functions/RepeatedFunction.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
=> account for common clause when generating AddHits sequence from repeated() function

Parser/AchievementBuilder.cs, Parser/Functions/RepeatedFunction.cs, Tests/Parser/AchievementBuilderTests.cs, ViewModels/NewScriptDialogViewModel.cs
As mentioned in #106, it's reasonable to expect always_false groups to be removed. There was already logic to do so as long as at least two alt groups remained because if only one alt group remained, it was merged into the core group.
I've added a second pass to the optimization code to remove all always_false alt groups after other optimization logic is applied (primarily promoting common alt logic to the core).
=> allow removal of always_false alt group even if only two alt groups remain

ViewModels/RequirementComparisonViewModel.cs, ViewModels/RequirementGroupViewModel.cs
allows an `always_true` condition to match any other `always_true` condition (i.e. `1=1` would match `2=2`)
also allows an `always_true` condition to match an empty group (fixes #128)
=> improve matching of always_true conditions

ViewModels/EditorViewModel.cs
Given the function definition
```
function trigger_in_level() => current_screen() == screen_in_game || // normal
current_screen() == screen_death      // after continue
```
The existing behavior shows
```
current_screen() == screen_in_game || // normal current_screen() == screen_death
```
as the tooltip when hovering over a reference to `trigger_in_level`. This changes the behavior to show
```
current_screen() == screen_in_game || current_screen() == screen_death
```
=> remove internal comments from expression tooltips

Parser/Functions/ComparisonModificationFunction.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Functions/OnceFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
This achievement was not generating an error when compiled, but did generate an error in the emulator as it resulted in a condition without a comparison:
```
achievement("Test", "Test", 1, bit1(0x1234))
```
The intent is that bit1 is non-zero, which is supported in some languages like C, but to support construction of AddHits/AddSource chains, we can't assume that to be true. Besides, a more explicit comparison ensures the logic is what the user intended and is more readable for less experienced programmers.
```
achievement("Test", "Test", 1, bit1(0x1234) != 0)
```
The first example will now generate an "Incomplete trigger condition" error.
=> report error when trigger condition has no comparison

Parser/Functions/RepeatedFunction.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, ViewModels/RequirementViewModel.cs
fixes #150 
extends #129 to also support combining flags in the common portion of the clause (represented by Core group of sub-trigger).
=> allow combining flags in common portion of AddHits chain

Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
fixes #154 
Expands the logical merging to all subclauses of a complex requirement. For AddSource, SubSource, and AddAddress, this still results in just comparing the left side. But for AndNext the operator and right side must also match (or be otherwise mergable) just like what was previously being done for the last requirement.
=> prevent incorrect merging of similar AndNext items in complex requirement

Parser/AchievementScriptInterpreter.cs, Parser/Functions/ArrayPopFunction.cs, Parser/Functions/LengthFunction.cs, Parser/Internal/ExpressionBase.cs, RATools.csproj, Tests/Parser/Functions/ArrayPopFunctionTests.cs, Tests/Parser/Functions/LengthFunctionTests.cs, Tests/RATools.Tests.csproj, changelog.txt
Compliments the `array_push()` function. Used to remove the last item from an array. If the array is empty, the return value is the integer constant `0`. To help differentiate between a 0 being popped off the array and reaching the end of the array, I've also implemented the `length()` function.
`length()` takes a single parameter. If it's an array or dictionary, it returns the number of elements in the container. If it's a string, it returns the number of characters in the string. Otherwise, it generates an error. Implements #140.
=> add array_pop() function

Data/Field.cs, Data/Leaderboard.cs, Parser/RichPresenceBuilder.cs, Parser/TriggerBuilderContext.cs, ViewModels/GameViewModel.cs, ViewModels/NewScriptDialogViewModel.cs, ViewModels/RichPresenceViewModel.cs, Views/NewScriptDialog.xaml
Implements #69 
The lookups and display string appear as additional items in the New Script dialog (initially not selected):
When selected, they will be included in the generated script, and will use any aliased memory reads defined on the right side of the dialog.
Lookups are defined near their associated memory when the memory has an aliased function:
```
// $0756: Set to 01 when large mario, 02 when fire-flower mario
function mario_powerup() => byte(0x000756)
PowerupLookup = {
0: "Small",
1: "Super",
2: "Fire",
}
```
Otherwise, they appear after the memory functions, but before the achievement functions. The rich presence functions appear at the end of the script.
There are a couple of caveats.
1) BCD memory reads generate a `bcd()` wrapper function that is not implemented.
2) …
=> support generating Rich Presence code when dumping achievements for existing game

Data/RequirementEx.cs, Parser/AchievementBuilder.cs, Parser/Functions/AchievementFunction.cs, Parser/Functions/TallyFunction.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
This loosens the restriction that mixing AndNext with OrNext is not allowed to allowing one AndNext as the singular AndNext can be moved to the front of the chain and not affect the logic.
Also fixes a NullReferenceException if `tally()` is passed an empty array.
=> allow one clause in complex chain to have AndNext

Parser/Internal/FunctionCallExpression.cs, Parser/Internal/IndexedVariableExpression.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/ArrayPopFunctionTests.cs, Tests/Parser/Functions/ArrayPushFunctionTests.cs, Tests/Parser/Functions/FormatFunctionTests.cs, Tests/Parser/Functions/LengthFunctionTests.cs, Tests/Parser/Internal/DictionaryExpressionTests.cs, Tests/Parser/Internal/FunctionCallExpressionTests.cs, ViewModels/EditorViewModel.cs
Provides more information on where an error occurred.
Only the final point of failure will be underlined in the editor. The other lines serve as context of where the error occurred, and can be double-clicked to jump to the related code.
=> show InnerError chain in Error List

Parser/Internal/DictionaryExpression.cs, Parser/Internal/FunctionCallExpression.cs, Parser/Internal/IndexedVariableExpression.cs, Tests/Parser/Internal/DictionaryExpressionTests.cs, Tests/Parser/Internal/FunctionCallExpressionTests.cs
Fixes #173 
When a dictionary is passed to a function without first being stored in a variable, any variables in the dictionary should be immediately expanded.
Also changes the dictionary lookup code to use a binary search for faster lookups.
=> only pass dictionary by reference if parameter was a variable

Parser/AchievementScriptInterpreter.cs, ViewModels/EditorViewModel.cs, ViewModels/GameViewModel.cs, Views/GameViewer.xaml
Separates processing the script from parsing it. The processing is offloaded to a background thread so the UI doesn't "hang" when processing a complex script. Parsing and syntax highlighting still happens on the UI thread, but takes almost no time, even with a complex script.
While processing, a progress bar is shown in the status bar. If a script is taking a long time, you can hover over the progress bar to see what it's processing. In this case, it's processing a `for` loop, which gives a bit of an idea what's running slowly, but not exactly where the code needs improvement.
=> make processing script asynchronous

Parser/Internal/FunctionCallExpression.cs, Parser/Internal/FunctionDefinitionExpression.cs, RATools.csproj, Services/Settings.cs, Services/Theme.cs, ViewModels/EditorViewModel.cs, ViewModels/GameViewModel.cs, ViewModels/MainWindowViewModel.cs, ViewModels/OptionsDialogViewModel.cs, Views/AchievementViewer.xaml, Views/Common.xaml, Views/GameViewer.xaml, Views/LeaderboardViewer.xaml, Views/OptionsDialog.xaml, Views/RichPresenceViewer.xaml, Views/ScriptViewer.xaml
Adds a new tab to the Settings dialog for changing colors used by the primary editors (has no effect on any of the existing dialogs).
In addition to changing each color individually, buttons are provided for quickly switching to the default theme and dark theme (implements #138). 
Users can also import/export their custom color choices. Here's a [blue theme](https://github.com/Jamiras/RATools/files/4901186/RATools-BlueTheme.zip) that I made.
=> Add ability to customize colors

Parser/Functions/ComparisonModificationFunction.cs, Parser/Functions/MemoryAccessorFunction.cs, Parser/Internal/FunctionCallExpression.cs, Parser/Internal/ParseErrorExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Parser/TriggerBuilderContext.cs, README.md, Tests/Parser/Functions/MemoryAccessFunctionTests.cs, Tests/Parser/Functions/MemoryAccessorFunctionTests.cs, Tests/RATools.Tests.csproj
Fixes #182
Modified the code that tries to report the most relevant error to include both the originating error and the causative error. This allows for more informative locating of the problematic issue. I've also expanded the error to report the expression it's having issue converting.
=> Improve error message when unable to generate a memory accessor

Parser/Internal/ComparisonExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
closes #183 
using the following truth table (where M is a value larger than the maximum value of A or B):
| original | converted |
|----------|------------|
| A == B | -A + B == 0 |
| A != B | -A + B != 0 |
| A > B | -A + B > M |
| A >= B | -A - 1 + B >= M |
| A < B | -A + B + M > M |
| A <= B | -A + B + M >= M |
Because of overflow, negative values will be very high positive values, so anything above the maximum value supported by either of the values is a negative value. For the less than comparisons, an additional M is added to ensure a non-negative value for the expected valid results. Added tests to rcheevos (https://github.com/RetroAchievements/rcheevos/pull/89) as proof.
=> convert indirect memory comparisons using different pointers to subsource sequence

Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
Since PauseIf only applies to the group it's in, it shouldn't be automatically deleted if both the core and an alt contain the same PauseIf clause.
=> don't remove duplicate PauseIf from alt if it's guarding something

Parser/Internal/FunctionCallExpression.cs, Tests/Parser/Internal/FunctionCallExpressionTests.cs
When `variable` is not found evaluating `unless(variable == 6)`, the error being generated was "no value provided for comparison parameter". This fixes the reporting to say "unknown variable: variable" instead.
=> return error evaluating parameters

Parser/AchievementScriptInterpreter.cs, Parser/Functions/LengthFunction.cs, Parser/Internal/DictionaryExpression.cs, Parser/Internal/IndexedVariableExpression.cs, Parser/Internal/InterpreterScope.cs, Tests/Parser/Functions/ArrayPopFunctionTests.cs, Tests/Parser/Functions/LengthFunctionTests.cs, Tests/Parser/Internal/DictionaryExpressionTests.cs, Tests/Parser/Internal/FunctionCallExpressionTests.cs, Tests/Parser/Internal/IndexedVariableExpressionTests.cs, Tests/Parser/Internal/InterpreterScopeTests.cs
Every time a dictionary is referenced, it's scanned to see if any of the keys or values changed. This PR adds a flag to the dictionary to indicate when this has happened so a dictionary that isn't changing can be used more efficiently.
This provides large performance gains on scripts that heavily rely on dictionaries.
=> optimize evaluation of constant dictionaries

Parser/AchievementScriptInterpreter.cs, Parser/Functions/AchievementFunction.cs, Parser/Functions/FormatFunction.cs, Parser/Functions/LeaderboardFunction.cs, Parser/Functions/RangeFunction.cs, Parser/Functions/RichPresenceDisplayFunction.cs, Parser/Internal/AssignmentExpression.cs, Parser/Internal/ExpressionBase.cs, Parser/Internal/ExpressionGroup.cs, Parser/Internal/ExpressionGroupCollection.cs, Parser/Internal/ForExpression.cs, Parser/Internal/FunctionCallExpression.cs, Parser/Internal/FunctionDefinitionExpression.cs, Parser/Internal/KeywordExpression.cs, Parser/Internal/LeftRightExpressionBase.cs, Parser/Internal/ParseErrorExpression.cs, Parser/Internal/ReturnExpression.cs, Parser/Internal/VariableExpression.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/DictionaryExpressionTests.cs, Tests/Parser/Internal/ExpressionBaseTests.cs, Tests/Parser/Internal/ExpressionGroupTests.cs, Tests/Parser/Internal/LeftRightExpressionBaseTests.cs, ViewModels/EditorViewModel.cs
simplifies debugging by merging `Line`, `Column`, `EndLine` and `EndColumn` into a single `Location` property.
=> use TextRange for ExpressionBase

Parser/Functions/RichPresenceLookupFunction.cs, Parser/Internal/FunctionDefinitionExpression.cs, Parser/RichPresenceBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
fixes a weird visual error where the dictionary definition gets highlighted when the dictionary is passed to a built-in function expecting a string or integer.
=> highlight variable (not definition of variable) when variable type is incorrect

Data/Field.cs, Tests/Data/FieldTests.cs
`hXXXX` is a valid representation of a hex constant, but since neither RATools nor the DLL generate hex constants, it hasn't been previously supported.
As it's entirely possible for the user to write rich presence or leaderboards using the syntax, it should be supported for the dumping feature.
=> support for hex constants in rich presence

Parser/Internal/ConditionalExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Internal/ConditionalExpressionTests.cs
fixes #210 
The problematic trigger has 2756 ANDed conditions. This is stored in a very sparse expression tree. When traversing the tree, somewhere around 2500 recursive calls are made, which is apparently enough to cause a stack overflow.
I've modified the `NormalizeNots` function to use a queue instead of recursion. This eliminates the recursive aspect, preventing the stack overflow.
The resulting achievement has 8550 conditions, and will probably need to be trimmed down.
=> replace recursive NormalizeNots algorithm with queue

Data/Requirement.cs, Data/RequirementEx.cs, Parser/AchievementBuilder.cs, Parser/AchievementScriptInterpreter.cs, Parser/Functions/RepeatedFunction.cs, Parser/Functions/TallyFunction.cs, Tests/Parser/Functions/TallyFunctionTests.cs, ViewModels/RequirementViewModel.cs
Allows marking conditions in a `tally()` call so they get turned into `SubHits` instead of `AddHits`.
```
tally(4, byte(0x1234) == 56, deduct(repeated(10, byte(0x2345) == 99)))
```
becomes:
```
AddHits 8-bit Mem 0x1234 == 56
SubHits 8-bit Mem 0x2345 == 99 (10)
0 == 1 (4)
```
Which says count how many times $1234 was 56, deduct how many times $2345 was 99 (maximum 10). If the total is at least 4, the logic is true.
If a `deduct` is present in a `tally()` call, the tally target will always be assigned to an `always_false` condition after the `AddHits` and `SubHits` are evaluated. This ensures that whatever other condition ended up being the final condition isn't artificially limited by the tally target.
=> add deduct() helper function for tally() function

ViewModels/LeaderboardViewModel.cs, Views/LeaderboardViewer.xaml
closes #200
appear as secondary links next to the Source link below the header and above the conditions.
=> add copy to clipboard commands for leaderboard title/description

Parser/AchievementBuilder.cs, Parser/LocalAchievements.cs, Tests/Parser/RegressionTests.cs
The first two lines of the `XXX-User.txt` file are metadata. The first is the version of the toolkit that generated the file, and the second is the name of the game retrieved from the server.
When the `XXX-User.txt` file is generated by RATools, the toolkit version is unknown, so a default value (`0.030`) is used. This PR will cause the version metadata to be the minimum version of the toolkit required for the generated logic. As I'm not sure of what changes were introduced before 0.76, anything that doesn't require at least 0.76 functionality will continue to output the default 0.30.
Note that this is purely meta-information and is not currently used by RATools or the RA_Integration.dll.
=> use minimum version in XXX-User.txt metadata

Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
fixes an issue where a group containing an invalid comparison with a hit count (i.e. `repeated(10, bit2(0x1234) == 0x04)`)  would cause the entire group to become `always_false()` instead of just the affected condition.
=> validate bit ranges when conditions have hitcounts

Parser/AchievementBuilder.cs, Parser/AchievementScriptInterpreter.cs, Parser/Functions/DisableWhenFunction.cs, RATools.csproj, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/DisableWhenFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, Tests/RATools.Tests.csproj
implements #106 
```
disable_when(byte(0x1234) == 1, until=byte(0x2345) == 2)
```
will generate
```
ResetNextIf byte(0x2345) == 2
PauseIf     byte(0x1234) == 1 (1)
```
The `until` clause is optional, and a HitCount greater than 1 can be specified using `repeated` syntax:
```
disable_when(repeated(5, byte(0x1234) == 1))
```
will generate
```
PauseIf byte(0x1234) == 1 (5)
```
If no `until` is specified, the pause will remain locked until the emulator is reset or another `never` in the trigger clears the lock. It is the responsibility of the author to put the external `never` in a different group than the pause lock.
=> add disable_when function

Parser/AchievementBuilder.cs, Parser/Functions/DisableWhenFunction.cs, Parser/TriggerBuilderContext.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Functions/DisableWhenFunctionTests.cs
`disable_when` was just injecting the `until` clause as a single `ResetNextIf` before then `when` clause. When the `when` clause is a `tally` sequence, a series of `AddHits` or `SubHits` conditions is generated. `ResetNextIf` does not traverse over an `AddHits` or `SubHits` condition, so the `until` was only affecting the first expression in the `tally` sequence. This expands on the `disable_when` functionality to inject the `until` clause after each `AddHits` or `SubHits` generated by the `tally` function. so they'll all be reset. The optimizer will still prefer to convert them back into a single `ResetIf` when possible
=> distribute ResetNextIf when building disable_when chain from tally

Parser/RichPresenceBuilder.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs, Tests/Parser/RichPresenceBuilderTests.cs, Tests/RATools.Tests.csproj
If a lookup has less than 10 items and at least half of them are duplicated, it will be collapsed into ranges.
If a lookup has 10 or more items and at least 20% of them are duplicated, it will be collapsed into ranges.
This attempts to balance backwards compatibility, readability, and leveraging the new feature.
The entire lookup has to still be defined in a single dictionary in the script, but you can use `for` with `range`s and arrays to populate redundant keys.
Before:
```
Lookup:Stage
0=Area A
1=Area F
2=Area F
3=Area C
4=Area D
5=Area D
6=Area E
7=Area E
8=Area A
9=Area C
10=Area B
11=Area B
12=Area E
13=Area F
14=Area B
15=Area G
16=Area G
17=Area D
18=Area C
19=Area G
```
After:
```
Lookup:Stage
0,8=Area A
1-2,13=Area F
3,9,18=Area C
4-5,17=Area D
6-7,12=Area E
10-11,14=Area B …
```
=> collapse duplicated rich presence strings into keyed ranges

Data/RequirementEx.cs, Parser/AchievementBuilder.cs, Parser/AchievementScriptInterpreter.cs, Parser/Internal/ComparisonExpression.cs, Parser/Internal/MathematicExpression.cs, Parser/LocalAchievements.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Internal/ComparisonExpressionTests.cs, Tests/Parser/RegressionTests.cs
This fixes an underflow error when using SubSource to determine if a value changes by at least a specific amount. Similar to [this](https://docs.retroachievements.org/SubSource-Flag/#using-subsource-to-count-specific-increments), but using `>`, `>=` as the comparison.
When using the equation `a - b >= n` to describe `a` being at least `n` higher than `b`: If `b` is greater than `a`, `(a-b)` will be negative, which becomes a very high positive number. Since a very high positive number is more than `n`, this makes the condition true, which is unexpected.
#100 tried to address this by adding an underflow adjustment whenever a memory reference was subtracted from another memory reference. However, when `b` was `prev(a)`, it wasn't being detected as a memory reference and the adjustment would …
=> fix underflow not detected when using prev

Parser/Internal/ExpressionBase.cs, Parser/Internal/FunctionCallExpression.cs, Parser/Internal/FunctionDefinitionExpression.cs, Parser/Internal/InterpreterScope.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
An anonymous function is defined as follows:
```
(parameterlist) => expression
```
If `parameterlist` is a single parameter, the parentheses can be omitted.
examples:
```
a = (i) => i + 1
b = i => i + 1
c = (i,j) => i + j
```
The long form can also be used for defining a function if more logic is required.
```
d = (i, j) {
if (i > j)
return i - j
return i + j
}
```
Parentheses cannot be omitted when using the long form, even if the `parameterlist` is a single parameter.
All of the above examples illustrate assigning a function to a variable. They can also be passed as function parameters, which is the primary use for anonymous functions:
```
e = somefunc(i => i + 1)
f = somefunc2((i, j) => i + j)
g = somefunc((i) {
if (i == 0)
return 0
return i + 1
})
```
=> support for anonymous functions

Parser/AchievementScriptInterpreter.cs, Parser/Functions/AllOfFunction.cs, Parser/Functions/AnyOfFunction.cs, Parser/Functions/IterableJoiningFunction.cs, Parser/Functions/NoneOfFunction.cs, Parser/Functions/SumOfFunction.cs, Parser/Internal/ArrayExpression.cs, Parser/Internal/ConditionalExpression.cs, Parser/Internal/DictionaryExpression.cs, Parser/Internal/ExpressionBase.cs, Parser/Internal/ForExpression.cs, Parser/Internal/FunctionCallExpression.cs, Parser/Internal/FunctionDefinitionExpression.cs, Parser/Internal/InterpreterScope.cs, Parser/Internal/MathematicExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, RATools.csproj, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/AllOfFunctionTests.cs, Tests/Parser/Functions/AnyOfFunctionTests.cs, Tests/Parser/Functions/NoneOfFunctionTests.cs, Tests/Parser/Functions/SumOfFunctionTests.cs, Tests/Parser/Internal/ComparisonExpressionTests.cs, Tests/RATools.Tests.csproj
Adds `any_of`, `all_of`, `none_of` and `sum_of` functions.
Each takes a list of inputs (either an array or a dictionary) and a predicate function. Each item in the array, or each key of the dictionary will be passed to the predicate function. The return values from the predicate function will be joined based on which helper function was called.
Because `range` generates an array, it can be used for the inputs.
-----
`any_of` generates a set of conditions that will be true if any individual condition is true
* `any_of([1,2,3], a => byte(0x1234) == a)` -> `byte(0x1234) == 1 || byte(0x1234) == 2 || byte(0x1234) == 3`
`all_of` generates a set of conditions that will be true only if all the conditions are true
* `all_of([1,2,3], a => byte(0x1234) != a)` -> `byte(0x1234) != 1 && byte(0x1234) != …
=> Iterable helper functions

ViewModels/GameViewModel.cs, ViewModels/GeneratedAchievementViewModel.cs, ViewModels/UpdateLocalViewModel.cs
fixes an issue where badges added to local achievements via the editor disappear when doing a delete/update cycle from the update local dialog
=> remember badge through delete/update cycle

Parser/AchievementScriptInterpreter.cs, Parser/Internal/ExpressionGroup.cs, Parser/Internal/ExpressionGroupCollection.cs, Tests/Parser/Internal/ExpressionGroupCollectionTests.cs, Tests/Parser/Internal/ExpressionGroupTests.cs
Fixes "go to source" not going to the correct line when lines are added or removed above the generating code.
=> update source line when generating group moves but doesn't change

Data/Achievement.cs, ViewModels/AchievementViewModel.cs, ViewModels/GameViewModel.cs, ViewModels/GeneratedAchievementViewModel.cs, ViewModels/NewScriptDialogViewModel.cs, Views/AchievementViewer.xaml
Core and Unofficial are mutually exclusive, so can be represented by a single ViewModel, which simplifies a little of the logic for calculating differences between published, local, and generated achievements.
=> use single child view model for Core and Unofficial published achievements

ViewModels/GameStatsViewModel.cs, Views/GameStatsDialog.xaml, Views/UserHistoryDialog.xaml
At some point, the achievement detail page change its user links from "/User/XXXX" to "/user/XXXX", so the parsing code could no longer find them.
Without an ApiKey, the additional data that is normally queried for the users who have been identified as having mastered the game is not queried, so all the data comes from the achievement detail pages. With the parsing code failing, the code could not identify any unlocks.
This fixes the URL matching to look for lowercase, and pops up a warning when all achievement unlocks for a user who has mastered a game cannot be determined from the achievement detail pages and no ApiKey is available.
=> fix game stats not showing up without an ApiKey

Parser/RichPresenceBuilder.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, Tests/Parser/RichPresenceBuilderTests.cs
Prevents emission of lookup entries that match the default value.
For example, if the following lookup were generated:
```
Lookup:OddOrEven
1=Odd
2=Even
3=Odd
4=Even
5=Odd
6=Even
7=Odd
*=Even
```
Since "Even" is the default string to display when no matching entry can be found, all items explicitly providing the value "Even" can be eliminated:
```
Lookup:OddOrEven
1=Odd
3=Odd
5=Odd
7=Odd
*=Even
```
=> don't generate RP lookup entries that match fallback value

Parser/Functions/MemoryAccessorFunction.cs, Tests/Parser/Functions/MemoryAccessorFunctionTests.cs, Tests/Parser/TriggerBuilderContextTests.cs
Fixes #242 
As the editor now supports negative offsets via integer overflow math without throwing an error when a dev attempts to do so, the code preventing the same in RATools is no longer required. This change aims for further feature parity with the editor.
=> Added support for negative relative offsets

Parser/Functions/PrevPriorFunction.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/PrevPriorFunctionTests.cs, Tests/RATools.Tests.csproj
fixes a "maximum recursion depth exceeded" error when wrapping a large addsource chain in prev().
=> simplify prev distribution over mathematic chain

Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
Generates an error when doing a comparison to a function result where the function result is also a comparison:
```
function f() => byte(0x1234) == 2
achievement("Title", "Description", 5, f() == 1)
```
Previously, this would process the `f()` call correctly, then append the `==1` as an `AddSource 0 == 1`.
=> report double comparison as error

Parser/AchievementScriptInterpreter.cs, Parser/Internal/BooleanConstantExpression.cs, Parser/Internal/ComparisonExpression.cs, Parser/Internal/ConditionalExpression.cs, Parser/Internal/DictionaryExpression.cs, Parser/Internal/ExpressionBase.cs, Parser/Internal/FunctionCallExpression.cs, Parser/Internal/FunctionDefinitionExpression.cs, Parser/Internal/IfExpression.cs, Parser/Internal/IntegerConstantExpression.cs, Parser/Internal/StringConstantExpression.cs, RATools.csproj, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/AllOfFunctionTests.cs, Tests/Parser/Functions/ArrayPushFunctionTests.cs, Tests/Parser/Functions/LengthFunctionTests.cs, Tests/Parser/Internal/BooleanConstantExpressionTests.cs, Tests/Parser/Internal/ComparisonExpressionTests.cs, Tests/Parser/Internal/ConditionalExpressionTests.cs, Tests/Parser/Internal/DictionaryExpressionTests.cs, Tests/Parser/Internal/FunctionCallExpressionTests.cs, Tests/Parser/Internal/FunctionDefinitionExpressionTests.cs, Tests/Parser/Internal/IfExpressionTests.cs, Tests/RATools.Tests.csproj, ViewModels/EditorViewModel.cs
Adds explicit `true` and `false` constants. 
These can be used like any other constant: assigned to variables, passed to or returned from functions, and stored in dictionaries or arrays.
They can be used directly in if statements (as return values from functions). `always_true` and `always_false` also behave as `true`/`false` for this purpose (which closes #253), but will still generate a `1==0` condition when used to construct a trigger.
**NOTE**: scripts that already define these will generate errors. In most cases, that can be fixed simply by removing the definitions. In cases where that isn't sufficient, they can be renamed. As variables are case sensitive, TRUE and FALSE or True and False would fix the problem.
=> boolean support

Parser/Functions/PrevPriorFunction.cs, Parser/Internal/ComparisonExpression.cs, Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/PrevPriorFunctionTests.cs, Tests/Parser/Internal/ComparisonExpressionTests.cs
```
function score() => bcd(word(0x1234))
achievement("Score!", "Get at least 50000 points", 5,
trigger = score() >= 50000 && prev(score()) < 50000
)
```
Previously, `prev(bcd(word(0x1234)))` would have generated an error about `bcd(word(0x1234))` not being a memory accessor.
The optimizer already factors out the `bcd()` call so the `bcd(word(0x1234)) >= 50000` is optimized to `word(0x1234) >= 327680`, but this happens after the script has generated a valid achievement. With this change, the `bcd()` is optimized out when evaluating the comparison (before generating the achievement), allowing the code to generate `prev(word(0x1234)) < 327680`.
=> allow using bcd() and prev() together

Data/RequirementEx.cs, Tests/Parser/AchievementBuilderTests.cs
fixes #258 
For a clause similar to:
```
AndNext a > x
OrNext  a < y
0 = 1 (1)
```
The hit count on the final condition must be migrated to the previous condition when the final condition is optimized out. The correctly optimized result is:
```
AndNext a > x
a < y (1)
```
=> preserve hitcount when optimizing out constant condition at end of clause

Parser/Functions/TriggerWhenFunction.cs, Tests/Parser/Functions/FlagConditionFunctionTests.cs
fixes #272 
The ResetNextIf was being prematurely optimized into a ResetIf.
=> don't optimize trigger clause too early

Data/Field.cs, Parser/Internal/ExpressionBase.cs, Parser/Internal/FloatConstantExpression.cs, Parser/LocalAssets.cs, Parser/TriggerBuilderContext.cs, Tests/Data/FieldTests.cs, Tests/Parser/Internal/FloatConstantExpressionTests.cs, Tests/Parser/LocalAchievementsTests.cs, Tests/Parser/RegressionTests.cs, Tests/Parser/TriggerBuilderContextTests.cs, ViewModels/NewScriptDialogViewModel.cs
fixes #266 
Updates all occurrences of double/float parse/tryparse and converting floats/doubles to strings to use the [InvariantCulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.invariantinfo?view=net-6.0).
=> use invariant culture for parsing/generating float values

Data/Requirement.cs, Data/RequirementEx.cs, Parser/AchievementBuilder.cs, Parser/Functions/MeasuredFunction.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Functions/MeasuredFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
Attempting to generate a new script for game 14772 was throwing an "Unhandled exception: Value must be positive." error. This was due to the line wrapping code for a complex expression not adjusting for the joiner (&&) correctly.
Additionally, that particular game used complex AndNext/OrNext chains that couldn't be converted back using the existing code. I've expanded the code to support them.
Finally, it used OrNext within a MeasuredIf, which was being split into alt groups. MeasuredIf only applies to the current group, so I've modified the code to not split it up.
=> fix New Script for game 14772

Tests/ViewModels/AssetViewModelBaseTests.cs, ViewModels/AssetViewModelBase.cs
When writing a local achievement without a badge, 00000 is written to the file. After assigning a badge and publishing the achievement, the published badge should be recognized and used. However, the logic was only checking for "0", not "00000".
=> don't preserve badge 00000 when merging

Tests/RATools.Tests.csproj, Tests/ViewModels/RequirementComparisonViewModelTests.cs, Tests/ViewModels/RequirementGroupViewModelTests.cs, Tests/ViewModels/RequirementViewModelTests.cs, ViewModels/NewScriptDialogViewModel.cs, ViewModels/RequirementGroupViewModel.cs, ViewModels/RequirementViewModel.cs
Handles a case where an "unless(a || b)" gets split into an "unless(a) || unless(b)". Previously, the OrNext requirement would be recognized as a removed requirement and the second PauseIf would be recognized as a new requirement. Now they're recognized as a single modified requirement, making the diff a bit easier to read.
=> better diff matching when an AndNext/OrNext chain is split up

ViewModels/OpenTicketsViewModel.cs
Fixes this:
(Alternative solution is to add null handling to line 456 of NewScriptDialogViewModel.cs but this solution means you don't have to add that if GetGameTickets is ever referenced again)
=> Fix "Object reference not set to an instance of an object" when dumping a game that has never received a ticket

Data/CodeNote.cs, RATools.csproj, Tests/Data/CodeNoteTests.cs, Tests/RATools.Tests.csproj, ViewModels/NewScriptDialogViewModel.cs
Mimics the DLL's support for parsing code note annotations.
Notably, adds support for sizes without spaces (`[32bit]`) and compound sizes (`[32-bit float]`)
=> support for more code note annotations

Data/RequirementEx.cs, Parser/AchievementBuilder.cs, Parser/Functions/AchievementFunction.cs, Parser/RequirementMerger.cs, RATools.csproj, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Functions/FlagConditionFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, Tests/Parser/Functions/TallyFunctionTests.cs, Tests/Parser/RequirementMergerTests.cs, Tests/RATools.Tests.csproj
Makes requirement merging slightly more aggressive. Allowing for things like "A < 1 || A > 1" to be turned into "A != 1".
Also improves logic for detecting when its safe to invert ResetIf and PauseIf conditions, allowing them to be more aggressively optimized.
=> Improve requirement merging optimizations

Parser/Functions/MeasuredFunction.cs, Tests/Parser/Functions/MeasuredFunctionTests.cs
```
measured(byte(0x1234) == 120, when = once(byte(0x2345) == 6 && byte(0x2346) == 7))
```
was being split into:
```
Measured   8-bit 0x1234 == 120
MeasuredIf 8-bit 0x2345 == 6
MeasuredIf 8-bit 0x2346 == 7 (1)
```
The once() applies to both subclauses, so the AndNext can't be converted to a MeasuredIf. This is correct:
```
Measured   8-bit 0x1234 == 120
AndNext    8-bit 0x2345 == 6
MeasuredIf 8-bit 0x2346 == 7 (1)
```
=> don't distribute MeasuredIf over subclauses of repeated condition

ViewModels/NewScriptDialogViewModel.cs
Invalid input RP:
```
Display:
Rayman was last seen at @Loc() with @lives() lives and @ting() ting's
```
When creating a New Script with that RP, the attempt to extract the parameters was failing. After fixing that, the attempt to create the code was failing. Both have been fixed, and the following is now generated:
```
rich_presence_display("Rayman was last seen at {0} with {1} lives and {2} ting's",
rich_presence_value("Loc", 0),
rich_presence_value("lives", 0),
rich_presence_value("ting", 0)
)
```
=> prevent IndexOutOfRangeException if RP macro has no parameter

Data/RequirementEx.cs, Parser/AchievementScriptInterpreter.cs, Parser/Functions/ArrayMapFunction.cs, Parser/Functions/TallyFunction.cs, Parser/Functions/TallyOfFunction.cs, RATools.csproj, Tests/Data/RequirementExTests.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/ArrayMapFunctionTests.cs, Tests/Parser/Functions/TallyFunctionTests.cs, Tests/Parser/Functions/TallyOfFunctionTests.cs, Tests/RATools.Tests.csproj
`array_map(array, predicate)` converts each element of array by passing it through the predicate function:
```
array_map([1,2,3], a => a*2)  =>  [2,4,6]
```
`tally_of(array, count, predicate)` creates a `tally` call by passing `array` through `predicate`:
```
tally_of([1,2,3], 2, a => once(byte(0x1234) == a))
=>
tally(2, once(byte(0x1234) == 1), once(byte(0x1234) == 2), once(byte(0x1234) == 3))
```
=> add array_map and tally_of functions

Data/Requirement.cs, Data/RequirementEx.cs, Parser/AchievementBuilder.cs, Parser/Functions/RepeatedFunction.cs, Tests/Data/RequirementExTests.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
fixes "only one never() clause" error when doing `repeated(3, b==1 && never(a==6 || a==7))`
=> support for OrNext in ResetNextIf clause

Data/RequirementEx.cs, Tests/Data/RequirementExTests.cs
The changes added in #299 were looking to extract the `repeated` subclause to convert it to a `tally`, but if the final condition had a hit target of 1, it would generate a `once` subclause and the `repeated` subclause would not be found.
=> fix IndexOutOfRange exception dumping achievement that would generate a 'tally(1,' clause

Source/ViewModels/OptionsDialogViewModel.cs, Source/Views/OptionsDialog.xaml
Adds a new field to the General tab of the Settings dialog for the user's API Key. Previously, the user had to manually add this to their ini file.
=> add API Key to settings dialog

Source/Parser/Functions/RichPresenceLookupFunction.cs, Source/Parser/TriggerBuilderContext.cs, Tests/Parser/Functions/RichPresenceLookupFunctionTests.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs, Tests/Parser/TriggerBuilderContextTests.cs
fixes #312 (constant "0" being converted to "" instead of "v0")
also detects a `rich_presence_lookup` of a constant and just evaluates it at compile time.
```
bools = {
0: "False",
1: "True"
}
rich_presence_display("1 is {0}",
rich_presence_lookup("Bools", 1, bools))
)
```
will generate
```
Display:
1 is True
```
without defining the lookup or the macro.
=> fix value constant of 0; optimize out rich_presence_lookup of constants

Source/Data/RequirementEx.cs, Tests/Parser/AchievementBuilderTests.cs
fixes #318 
modifies the logic that removes the `always_false()` from the `tally()` to search forward, instead of backward, preventing the removal of part of the `when` clause.
=> fix dumping measured(tally(), when=)

Source/Data/Requirement.cs, Tests/Parser/AchievementBuilderTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/987365591746744360
```
rich_presence_display("{0}",
rich_presence_value("Count", sum_of(range(2, 4), f => low4(f)/low4(f)))
)
```
was generating
```
@Count(A:0=0_A:0=0_M:0=1)
```
instead of the expected
```
@Count(A:0xL000002/0xL000002_A:0xL000003/0xL000003_M:0xL000004/0xL000004)
```
=> fix optimization of division by self

Source/Data/Field.cs, Source/Data/Requirement.cs, Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/ComparisonExpression.cs, Source/Parser/Expressions/ConditionalExpression.cs, Source/Parser/Expressions/Trigger/AlwaysFalseExpression.cs, Source/Parser/Expressions/Trigger/AlwaysTrueExpression.cs, Source/Parser/Expressions/Trigger/BinaryCodedDecimalExpression.cs, Source/Parser/Expressions/Trigger/MemoryAccessorExpression.cs, Source/Parser/Functions/AlwaysFalseFunction.cs, Source/Parser/Functions/AlwaysTrueFunction.cs, Source/Parser/Functions/BitFunction.cs, Source/Parser/Functions/MemoryAccessorFunction.cs, Source/Parser/Functions/PrevPriorFunction.cs, Source/Parser/Internal/ExpressionBase.cs, Source/Parser/Internal/IExecutableExpression.cs, Source/Parser/Internal/ITriggerExpression.cs, Source/Parser/ScriptInterpreterAchievementBuilder.cs, Source/Parser/TriggerBuilderContext.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Expressions/ArrayExpressionTests.cs, Tests/Parser/Expressions/ComparisonExpressionTests.cs, Tests/Parser/Expressions/DictionaryExpressionTests.cs, Tests/Parser/Expressions/FunctionDefinitionExpressionTests.cs, Tests/Parser/Expressions/MathematicExpressionTests.cs, Tests/Parser/Functions/ArrayPushFunctionTests.cs, Tests/Parser/Functions/MemoryAccessorFunctionTests.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs
Provides a psuedo-compiled representation of memory accessors (`byte()`, `word()`, etc) so the virtual functions don't have to be repeatedly examined while they're passed around.
=> initial support for intermediate representation of achievement logic

Source/ViewModels/LeaderboardViewModel.cs, Source/ViewModels/RichPresenceViewModel.cs
Fixes the "Copy to Clipboard" link for Rich Presence and the "Copy Title to Clipboard" and "Copy Description to Clipboard" links for Leaderboards.
=> fix broken Copy to Clipboard commands

Source/ViewModels/GameStatsViewModel.cs, Source/ViewModels/UserMasteriesViewModel.cs
fixes an issue where user master time would be 0 minutes for a game with lots of players
=> allow fetching per-user data when populating user mastery dialog

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/ComparisonExpression.cs, Source/Parser/Expressions/FunctionCallExpression.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Source/Parser/Functions/MeasuredFunction.cs, Source/Parser/Functions/OnceFunction.cs, Source/Parser/Functions/RepeatedFunction.cs, Source/Parser/Functions/TallyFunction.cs, Source/Parser/ParameterInitializationContext.cs, Source/Parser/ScriptInterpreterAchievementBuilder.cs, Tests/Parser/Expressions/FunctionCallExpressionTests.cs, Tests/Parser/Expressions/Trigger/MemoryAcessorExpressionTests.cs, Tests/Parser/Functions/MeasuredFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs, Tests/Parser/Functions/TallyFunctionTests.cs, Tests/Parser/Regression/RegressionTests.cs, Tests/Parser/TriggerBuilderContextTests.cs
Prevents converting `measured(A + 20 < 80)` to `measured(A < 60)`, which ensures that the reported measured progress in the app still reports "(X/80)". The optimization is still allowed for `measured(A + 20 < 80, format="percent")`. as the value is not being reported directly to the user.
**NOTE:** As part of this change, `repeated(0, X)` and `tally(0, X, Y)` are no longer supported outside of measured value expressions (i.e. leaderboard values or rich presence values). Previously, those constructs could be used to trick the optimizer into ignoring an OrNext/AndNext chain giving the author more control over the resulting syntax. This was not intended. When a script says `trigger = repeated(0, X)`, it's implying that the trigger should only fire if X has never been true. That construct is …
=> Don't optimize measured comparison if it changes the measured target

Source/Data/Requirement.cs, Source/Parser/AchievementBuilder.cs, Source/Parser/Functions/ComparisonModificationFunction.cs, Source/Parser/Functions/TallyFunction.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs
Fixes an issue where a `never` within a `tally` would lose the ResetNextIf.
```
tally(8, byte(0x1234) != prev(byte(0x1234)) && never(byte(0x2345) == 2)
```
Would generate
```
AndNext byte 0x2345 != 2
byte 0x1234 != delta byte 0x1234 (8)
```
Instead of
```
ResetNextIf byte 0x2345 == 2
byte 0x1234 != delta byte 0x1234 (8)
```
Reported here: https://discord.com/channels/310192285306454017/936655398725902356/1015723213457731704
#204 added ResetNextIf support to `repeated`, but it was never added to `tally`.
=> support for ResetNextIf in tally

Source/RATools.csproj, Source/ViewModels/GameProgressionViewModel.cs, Source/ViewModels/GameStatsViewModel.cs, Source/ViewModels/UserMasteriesViewModel.cs, Source/Views/GameProgressionDialog.xaml, Source/Views/GameProgressionDialog.xaml.cs, Source/Views/GameStatsDialog.xaml, Source/Views/MainWindow.xaml.cs
Provides a breakdown of rough estimates for playtime required to reach each achievement in a set.
Times are estimated for each user using the same logic as mastery calculations (achievements more than four hours apart are considered to be in separate sessions and an adjustment is applied to each session to simulate time spent playing before earning the first achievement in the session or after earning the last). These individual estimates are averaged for each achievement, then the list is sorted by the average.
This functionality leverages the data retrieved for the game mastery times, so it can be accessed as a sub-dialog off the Game Mastery dialog.
=> add game progression dialog

Source/Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Expressions/Trigger/RequirementClauseExpression_Tests.cs
Prevent `float(0x1234) < 0` from being converted to `always_false()`. The optimizer assumed that all memory reads were unsigned. Floating point memory reads may be signed, so the value can logically be less than 0. Using `float(0x1234) < 0.0` is a valid workaround.
https://discord.com/channels/310192285306454017/936655398725902356/1019710133800022066
=> don't restrict float comparisons to integer ranges

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Tests/Parser/Expressions/Trigger/MemoryValueExpressionTests.cs, Tests/Parser/Expressions/Trigger/RequirementClauseExpression_Tests.cs
prevents "combination of &&s and ||s is too complex for subclause" error if subclause is redundant with parent.
i.e.
```
once(A && B && (C || (A && B && D) || E))
```
The `A && B` can be removed from `A && B && D`, leaving `once(A && B && (C || D || E))`, which can be properly processed.
=> simplify nested AND containing elements in parent AND condition

Source/Parser/AchievementBuilder.cs, Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/Trigger/RequirementConditionExpression.cs, Source/Parser/RequirementMerger.cs, Tests/Parser/Expressions/Trigger/RequirementClauseExpression_Tests.cs, Tests/Parser/Regression/RegressionTests.cs
fixes `x > 5.0 && x < 7.2` incorrectly being turned into `always_false()`
=> fix intersection of float comparisons

Source/Parser/LocalAssets.cs
prevents "corruption" of notes containing newlines without quotes
=> ensure notes with newlines but no quotes are properly escaped

Source/Parser/Expressions/ForExpression.cs, Source/Parser/Internal/ExpressionTokenizer.cs
given a script:
```
a = 0
for b in range(0,5) {
a = a + 1
}
```
if a comma was injected into the middle statement:
```
a = 0
for b in range(0,5) {
a = a, + 1
}
```
the editor would report several errors:
* unexpected character: ,
* unexpected character: +
* unexpected character: }
When the comma was removed, only the errors on the modified line would be corrected, leaving the third error. Additionally, the `for` line would lose its syntax highlighting.
This fixes both of the above errors by retaining the expressions for the `for` statement through the error state and resolution.
=> fix for loop retaining error after correction

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Functions/SubstringFunction.cs, Tests/Parser/Functions/SubstringFunctionTests.cs
as suggested in #345 (under 'splitting' header).
inputs:
* `string` - the string to be split
* `offset` - the 0-based index to start copying from
* `length` - the number of characters to capture (optional - if not specified, the remaining portion of the string will be captured)
`offset` may be a negative number, in which case copying will start from that many characters from the end of the string.
`length` may be a negative number, in which case copying will stop that many characters from the end of the string.
if any combination of `offset` and `length` creates an invalid selection, an empty string will be returned.
examples:
`substring("abcdef", 3)` => `"def"`
`substring("abcdef", 0, 3)` => `"abc"`
`substring("abcdef", 2, 2)` => `"cd"`
`substring("abcdef", 2, -1)` => `"cde"` …
=> add substring() function

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Functions/AsciiStringEqualsFunction.cs, Source/Parser/Functions/UnicodeStringEqualsFunction.cs, Tests/Parser/Functions/AsciiStringEqualsFunctionTests.cs, Tests/Parser/Functions/UnicodeStringEqualsFunctionTests.cs
As suggested in #345 (under 'matching strings in memory' header). 
I believe this addresses the underlying desires posited in #141.
inputs:
* `address` - the address to match against the first byte of the string
* `string` - the string to match
* `length` - the number of characters to match. if longer than the string, null padding will be validated. if omitted, the length of the string will be used.
examples:
`ascii_string_equals(0x1234, "test")`
=> `dword(0x1234) == 0x74736574`
`ascii_string_equals(dword(0x1234) + 0x20, "Hello!", 7)`
=> `dword(dword(0x1234) + 0x20) == 0x6C6C6548 && tbyte(dword(0x1234) + 0x24) == 0x00216F`
`unicode_string_equals(0x1234, "test")`
=> `dword(0x1234) == 0x00650074 && dword(0x1238) == 0x00740073`
=> add ascii_string_equals() and unicode_string_equals() functions

Source/Data/Field.cs, Source/Data/RequirementEx.cs, Source/Parser/Expressions/Trigger/MemoryAccessorExpressionBase.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/AchievementBuilderTests.cs, Tests/Parser/Expressions/Trigger/MemoryAcessorExpressionTests.cs, Tests/Parser/Functions/MemoryAccessorFunctionTests.cs
bitwise and has a lower precedence than arithmetic, so the `byte(dword(0x1234) & 0x1FFFFFF + 0x30)` being dumped would get treated as `byte(dword(0x1234) & (0x1FFFFFF + 0x30))`. This update the dumper to put explicit parenthesis around the bitmask so it can be interpreted correctly as `byte((dword(0x1234) & 0x1FFFFFF) + 0x30)`.
Also adds logic to use smaller memory reads when masking (i.e. `dword(0x1234) & 0xFFFF` => `word(0x1234)`)
=> add parenthesis when dumping masked pointers

Source/Parser/AchievementBuilder.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Tests/Parser/Functions/AchievementFunctionTests.cs
instead of just saying "trigger is not a requirement", attempt to highlight the nested condition leading to the error.
=> more informative error when function call in trigger cannot be evaluated

Source/ViewModels/RequirementViewModel.cs, Source/Views/AssetViewer.xaml, Source/Views/Common.xaml, Tests/ViewModels/RequirementViewModelTests.cs
Implements #386 
If a code note has more than one line, only the first line is shown, and a ellipsis "button" is displayed that has a tooltip with the entire code note.
I'm not going to include an option to toggle the behavior at this time. I feel that as long as the important information is in the first line of the code note, hiding the rest of the information when viewing an overview of the "compiled" code is cleaner.
=> only show first line of note in requirements view

Source/ViewModels/AchievementViewModel.cs, Source/ViewModels/MainWindowViewModel.cs, Source/ViewModels/ViewAchievementsViewModel.cs, Source/Views/MainWindow.xaml, Source/Views/MainWindow.xaml.cs, Source/Views/ViewAchievementsDialog.xaml, Source/Views/ViewAchievementsDialog.xaml.cs
Adds a new item to the View menu that shows the list of achievements as they would appear in the overlay.
Includes an "Export" button in the lower left that generates a CSV of the ID, title, description, and points for all achievements (#369)
=> add Achievement List dialog

Source/Parser/Internal/ExpressionBase.cs, Tests/Parser/Expressions/FunctionCallExpressionTests.cs
instead of the more generic "unexpected character )" and "invalid expression" errors.
https://discord.com/channels/310192285306454017/936655398725902356/1107470058663444521
=> report trailing comma error when parameter list ends in ',)'

Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Internal/ExpressionBase.cs, Tests/Parser/Expressions/FunctionDefinitionExpressionTests.cs
Fixes #395
Because the error is being generated when parsing, there's no context to know whether or not the variable is actually defined, or what its value is. To work around that, I've opted to allow variables to be assigned to default parameters, but not variable expressions (i.e. "param3=a" is okay, but "param3=a+1" is not.)
As a result, the default parameter becomes a variable reference, which is evaluated when the function is called. Assuming this functionality is only used with "constant" variables, the user won't notice.
=> allow 'constants' to be used as values in default parameters

Source/Parser/Expressions/FunctionCallExpression.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Internal/ExpressionBase.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Expressions/Trigger/BehavioralRequirementExpression_Tests.cs, Tests/Parser/Functions/AchievementFunctionTests.cs, Tests/Parser/Functions/OnceFunctionTests.cs, Tests/Parser/Functions/RepeatedFunctionTests.cs
Instead of just saying "trigger is not a requirement", include a nested error stating why. i.e. "Cannot convert memoryaccessor to requirement".
https://discord.com/channels/310192285306454017/936655398725902356/1116390313548845136
=> improve messaging for improperly structured requirements

Source/Data/Requirement.cs, Tests/Data/RequirementExTests.cs, Tests/RATools.Tests.csproj
fixes dumping syntax related to https://github.com/Jamiras/RATools/issues/396#issuecomment-1573783500
=> fix dumping measured(tally(0, X && Y))

Source/Parser/AchievementBuilder.cs, Tests/Parser/AchievementBuilderTests.cs
Closes #404 
While logically correct, converting a ResetNextIf attached to a Trigger condition into a ResetIf causes the challenge indicator to disappear when the ResetIf is true. Clearing the hits on the Trigger should not cause the challenge indicator to be hidden as long as the non-Trigger conditions remain true.
=> don't change ResetNextIf to ResetIf when attached to a Trigger condition

Source/Parser/Expressions/IntegerConstantExpression.cs, Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/RequirementConditionExpression.cs, Source/Parser/Internal/ExpressionBase.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs, Tests/Parser/Expressions/Trigger/RequirementClauseExpression_Tests.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
prevents infinite loop trying to process
```
(word(0x18294A) * 10 - word(0x182946) * 8) < 0x80000000
```
=> don't try to underflow comparisons to very large numbers

Source/Parser/Expressions/Trigger/TalliedRequirementExpression.cs, Source/ViewModels/GameDataSnapshotViewModel.cs, Tests/Parser/Functions/TallyFunctionTests.cs
The logic:
```
tally(5, good(), deduct(bad()))
```
Would generate the code:
```
SubHits bad()
good() (5)
```
This would clamp the number of times `good()` could be tallied to 5, so if any `bad()`s were tallied, the logic would never be true.
The correct code would be:
```
SubHits bad()
AddHits good()
always_false() (5)
```
Which allows `good()` to be tallied more than 5 times to counteract any deductions made by `bad()`. If There needs to be a limit on `good()`, it can be wrapped in it's own `repeated()`.
=> always add always_false() clause when tally contains a deduct

Source/Data/Requirement.cs, Tests/Data/RequirementTests.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
Fixes an issue where a modification to an AddSource constant would not be flagged as a modification.
Expected:
Actual:
=> fix modification detection of AddSource constant

Source/Parser/Expressions/Trigger/MemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/RequirementConditionExpression.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1154136605683093534
=> prevent loss of modifier when comparing two similar pointer chains

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Functions/AsciiStringEqualsFunction.cs, Source/Parser/Functions/IdentityTransformFunction.cs, Source/Parser/Functions/UnicodeStringEqualsFunction.cs, Tests/Parser/Functions/AsciiStringEqualsFunctionTests.cs, Tests/Parser/Functions/UnicodeStringEqualsFunctionTests.cs
Allows passing `prev`, `prior`, or even a custom function to modify each chunk of the generated comparison.
https://discord.com/channels/310192285306454017/936655398725902356/1124756200001634387
```
ascii_string_equals(0x1234, "banana", transform = a => prev(a))    
```
becomes
```
d0xX001234=1634623842_d0x 001238=24942
```
and because `prev` is already a function that accepts a single accessor parameter an returns an accessor, it can be used directly:
```
ascii_string_equals(0x1234, "banana", transform = prev)    
```
=> Add transform parameter to ascii_string_equals and unicode_string_equals

Source/Data/CodeNote.cs, Tests/Data/CodeNoteTests.cs
fixes #428 
It's choking on the code note:
```
Bitflags for Sea chart (possible array of ~40 bytes)
```
It sees both "bit" and "byte" in the same string. After it discards the "bit" portion because it's not explicitly "bit" or "bits", the offset it found for "byte" is no longer correct and results in a read past the end of the string.
=> fix issue parsing code note containing bitflags string and array size notation

Source/Parser/Expressions/IfExpression.cs, Source/Parser/Expressions/VariableExpression.cs, Tests/Parser/Expressions/IfExpressionTests.cs, Tests/Parser/Expressions/VariableExpressionTests.cs
Fixes https://discord.com/channels/310192285306454017/533411674162593812/1201574594327347281
```
if (someBoolean)
{
do_something()
}
```
was being parsed incorrectly. The `(someBoolean) { do_something() }` was being seen as an anonymous function definition. Then, when the `if` was evaluated, the anonymous function definition was not convertible to a boolean and an error was generated.
Solution: don't greedily assume anonymous function definition following an `if` keyword.
=> fix anonymous function error using boolean variable directly in if statement

.gitignore, RATools.sln, Source/Data/Achievement.cs, Source/Data/AssetBase.cs, Source/Data/Leaderboard.cs, Source/Data/RATools.Data.csproj, Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/RATools.Parser.csproj, Source/RATools.csproj, Source/ViewModels/AssetViewModelBase.cs, Source/ViewModels/GameViewModel.cs, Source/rascript-cli/Program.cs, Source/rascript-cli/RAScriptCLI.cs, Source/rascript-cli/rascript-cli.csproj, Tests/RATools.Tests.csproj, Tests/Regression/RegressionTests.cs, Tests/Regression/ScriptTests.cs
Allows rascript files to be processed from the command line for people who prefer to use other editors (like VSCode).
It does not provide the same feature set however. There's no way to see what changes are being applied to individual achievements, and only update specific achievements. The tool effectively does an Update Local with everything in the Update column checked. It will abort if there are _any_ errors.
The tool has one required parameter.
```
rascript-cli 1.13.0
========================
Usage: rascript-cli [-v] [-q] [-i script] [-o outdir] [-a author]
-v            (optional) enabled verbose messages
-q            (optional) disable all messages
-i script     specifies the input file to process
-o outdir     (optional) specifies the output directory to write to [default: …
```
=> add rascript-cli command line interpreter

Source/Parser/Expressions/AssignmentExpression.cs, Source/Parser/Expressions/FunctionCallExpression.cs, Source/Parser/Expressions/IndexedVariableExpression.cs, Source/Parser/Expressions/VariableExpression.cs, Tests/Parser/Expressions/DictionaryExpressionTests.cs
Fixes an issue where modifying a nested dictionary did not work:
```
dict = {"a": {"b": 3} }
dict["a"]["b"] = 5
achievement("test", "test", dict["a"]["b"], trigger=...)
```
Would generate an achievement worth 3 points, not 5.
This is a result of the temporary variable used for storing `dict["a"]` evaluating the dictionary instead of referencing it. By evaluating it, a copy was made, and the `["b"] = 5` modification was applied to the copy.
The same problem occurs when using a non-anonymous intermediate variable:
```
dict = {"a": {"b": 3} }
t = dict["a"]
t["b"] = 5
achievement("test", "test", dict["a"]["b"], trigger=...)
```
`t` was a copy of `dict["a"]`, so the modification was applied to the copy.
When dictionaries (or arrays) are passed to a function, they're done so by reference, so …
=> allow assigning values to nested dictionaries

Source/Views/MainWindow.xaml.cs
Minor change to exception reporting dialog.
Before:
After:
Hopefully, this directs users to the log file when reporting issues.
=> use TaskDialog for reporting exceptions

Source/Parser/Functions/IterableJoiningFunction.cs, Tests/Parser/Functions/AllOfFunctionTests.cs, Tests/Parser/Functions/AnyOfFunctionTests.cs, Tests/Parser/Functions/ArrayMapFunctionTests.cs, Tests/Parser/Functions/NoneOfFunctionTests.cs, Tests/Parser/Functions/SumOfFunctionTests.cs, Tests/Parser/Functions/TallyOfFunctionTests.cs
=> fix NullReferenceException when predicate doesn't return a value

Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Tests/Parser/Expressions/Trigger/RequirementClauseExpression_Tests.cs
fixes #456
The requirement merging code was ignoring the mask, so instead of seeing
```
a & 0xFFEF == 0x4 && a < 0x10
```
It only saw
```
a == 0x4 && a < 10
```
Since a value of 4 is automatically less than 10, it jut dropped the less than 10 check.
I've modified the logic to not compare two requirements if their modifiers differ.
=> include modification when looking for equal ModifiedMemoryAccessors

Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Tests/Parser/Internal/RequirementsOptimizerTests.cs
fixes #471 
Evaluation of the provided script resulted in the following condition:
```
(always_false() || always_false()) && (byte(0x100000) == 0 || byte(0x100000) == 1)
```
Since you can't AND two OR groups, it tried to cross multiply them to get four AND conditions. To minimize the number of resulting groups, a first pass is made to eliminate the `always_false`s, which left the left clause empty and broke the cross-multiplication logic.
Solution: If clause ends up empty, discard it.
=> discard empty subclause when cross-multiplying ORs

Source/Parser/Functions/TallyFunction.cs, Tests/Parser/Expressions/FunctionCallExpressionTests.cs, Tests/Parser/Functions/TallyFunctionTests.cs, Tests/Parser/Internal/RequirementsOptimizerTests.cs
The logical construct to capture two of three things happening:
```
tally(2, once(A) || once(B) || once(C))
```
is incorrect. It should be written as:
```
tally(2, once(A), once(B), once(C))
```
In the first case, it generates an OrNext chain:
```
OrNext A (1)
OrNext B (1)
AddHits C (1)
false (2)
```
This is wrong because line 3 can only ever generate a single hit, so the target of 2 hits on line 4 can never be reached.
It also doesn't correctly represent the original code. Converting it back to RAScript generates `tally(2, once(once(once(A) || B) || C))`.
The `tally` function will now detect this and report an error:
> Cannot tally subclause with multiple hit targets
=> generate error if passing or chain to tally

Source/Parser/Expressions/DictionaryExpression.cs
There's an edge case involving dictionaries which keys 
use a mixture of positive and negative integers. For example:
```fsharp
SONG_ABOUT_A_GIRL_UNPLUGGED          = 0x6b450446
SONG_AMERICAN_WOMAN                  = 0x49e39403
SONG_BAND_ON_THE_RUN                 = 0x57c4ea83
SONG_BEAT_IT                         = 0x69e63d11
SONG_BEAUTIFUL_DISASTER              = 0x75a03c4c
SONG_CRAZY_TRAIN                     = 0x1ac0a35e
SONG_DAMMIT                          = 0x131e5f8b
SONG_DO_IT_AGAIN                     = 0xcaac63ee
SONG_LOVE_REMOVAL_MACHINE            = 0xf991002d
SONG_THE_MIDDLE                      = 0x417b1aa8
SONG_MISERY_BUSINESS                 = 0x2d1f51f8
SONG_INFO = {
SONG_ABOUT_A_GIRL_UNPLUGGED: "About A Girl",
SONG_AMERICAN_WOMAN        : "American Woman"
// etc...
}
for …
```
=> correct IntegerConstantExpression comparison in DictionaryEntry Compare

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Source/Parser/Internal/TriggerBuilderContext.cs, Tests/Parser/AchievementScriptInterpreterTests.cs
#448 added support for a script-wide minimum version, derived from the minimum version needed from all defined achievements, leaderboards, and rich presence.
This allows the author to explicitly specify a script-wide minimum version (which may be automatically increased if any achievement, leaderboard, or rich presence features require a higher minimum version).
The primary use case of this is to disable the logic that converts a series of ANDed ORs into multiple alt groups and use OrNext instead. Previously, authors had to explicitly state they wanted to use OrNext by using the `__ornext` helper function.
Note: This does not prevent the optimizer from generating simple alts: `A && (B || C)` will still get alts for `B` and `C`, even if the minimum version is set above 0.78. `__ornext` can …
=> add #MinimumVersion header meta-comment

Source/Parser/Expressions/ComparisonExpression.cs, Tests/Parser/Functions/MeasuredFunctionTests.cs
=> don't move constants in percent measured clauses

Source/Data/Requirement.cs, Source/Data/RequirementOperator.cs, Source/Data/RequirementType.cs, Source/Parser/Internal/RequirementMerger.cs, Source/Parser/Internal/RequirementsOptimizer.cs, Source/Parser/ScriptBuilderContext.cs
Allows writing
```
r.Operator = r.Operator.OppositeOperator();
```
instead of
```
r.Operator = Requirement.GetOpposingOperator(r.Operator);
```
=> move Requirement enum helpers into extension methods

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/ViewModels/GameStatsViewModel.cs, Tests/Parser/Expressions/ComparisonExpressionTests.cs
Fixes #503
Checks for intentional underflow adjustment before looking for indirect memory accessors.
=> prevent infinite loop when summation chain contains subtraction and pointers

Source/Parser/Expressions/ExpressionGroupCollection.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Tests/Parser/Expressions/FunctionDefinitionExpressionTests.cs
Fixes an issue where a parse error within a function defined with shorthand would cause the function to disappear from the parse tree, and wouldn't reappear until the editor was refreshed, even if the parse error was corrected.
=> fix broken parser if shorthand function body doesn't parse

Source/Parser/Expressions/Trigger/FieldFactory.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/RequirementConditionExpression.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
Fixes #504 
For the first error (`~byte(0x1234) * ~byte(0x2345)`), the inversion flag was just being ignored. That has been fixed.
For the second error (`~byte(0x1234) > ~byte(0x2345)`), inverting both sides is intentional. The logic was only testing the equality case, where the operator should not be modified. When testing greater than/less than, the operator should also be reversed, so the expected outcome would be `byte(0x1234) < byte(0x2345)`.
Here's a simplified truth table showing that reversing the operator is correct if the inversion is removed from both sides:
```
< 00 01 10 11     > 11 10 01 00
00  N  Y  Y  Y    11  N  Y  Y  Y
01  N  N  Y  Y    10  N  N  Y  Y 
10  N  N  N  Y    01  N  N  N  Y
11  N  N  N  N    00  N  N  N  N
```
=> fix missing inversion flag on modifier

Source/Data/RequirementEx.cs, Tests/Parser/Functions/DisableWhenFunctionTests.cs
https://discord.com/channels/310192285306454017/936655398725902356/1270636041669316608
```
disable_when(byte(0x1234) & 7 == 3 || byte(0x2345) == 8)
```
should generate:
```
AddSource byte 0x1234 & 7
OrNext    value     0 = 3
PauseIf   byte 0x2345 = 8 (1)
```
but was improperly becoming
```
AddSource byte 0x1234 & 7
PauseIf   byte 0x2345 = 8 (1)
```
The `OrNext 0 = 3` was being discarded as it is effectively never true. The optimizer was ignoring the fact that it's dependent on the AddSource on the previous line.
=> fix issue where 'OrNext 0=1' following an AddSource was being optimized out

Source/Parser/Internal/RequirementsOptimizer.cs, Tests/Parser/Internal/RequirementsOptimizerTests.cs
fixes #511 
If a trigger contains a single ResetNextIf, the optimizer would turn it into a ResetIf. It was also doing this for ResetNextIfs attached to a PauseIf, but would move it into an Alt group so the PauseIf wouldn't prevent the ResetIf from triggering.
Normally, the ResetNextIf clause for a PauseLock is unrelated to the achievement triggering (like being back at the title screen). However, it is possible that the ResetNextIf attached to the PauseIf could still be true when the achievement should trigger. When changed to a ResetIf, that would prevent the achievement from triggering. Logically, this should be allowed. Disabling a PauseLock should not also disable the achievement.
As such, a ResetNextIf attached to a PauseIf will no longer be converted to a ResetIf and moved to an …
=> don't turn ResetNextIf attached to PauseIf into ResetIf

Source/Data/Requirement.cs, Source/Data/RequirementOperator.cs, Source/Data/Version.cs, Source/Parser/Expressions/Trigger/FieldFactory.cs, Source/Parser/Expressions/Trigger/MemoryAccessorExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Source/Parser/ScriptBuilderContext.cs, Source/ViewModels/ConditionsAnalyzerViewModel.cs, Tests/Data/RequirementTests.cs, Tests/Parser/Expressions/Trigger/MemoryAcessorExpressionTests.cs, Tests/Parser/Expressions/Trigger/ModifiedMemoryAcessorExpressionTests.cs
Allows things like `byte(0x1234) % 10`, but not `byte(0x1234) * 3 % 10`.
=> support for simple runtime modulus

Source/Parser/Expressions/IndexedVariableExpression.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Expressions/Trigger/MemoryAccessorExpressionTests.cs
Instead of saying "Index 2 is not in range (0--1)", will now say "Cannot index empty array".
=> improve error message when indexing empty array

Source/Data/Requirement.cs, Source/Data/RequirementGroup.cs, Source/Data/Trigger.cs, Source/Parser/Functions/LeaderboardFunction.cs, Tests/Parser/Functions/LeaderboardFunctionTests.cs
closes #457 
If a leaderboard's submit condition is true in the frame where it's start condition becomes true, it will automatically submit. As a result, logically, if the submit and start condition are the same, the submit condition can be simplified to `always_true()`.
This PR changes it so that if a leaderboard's submit conditions _exactly_ match a leaderboard's start conditions, the submit condition will be changed to `always_true()`. This does not attempt to match conditions in an alternate order, or a subset of conditions, though both could logically be converted.
=> replace redundant leaderboard submit with always_true

Source/ViewModels/AchievementViewModel.cs, Source/Views/AchievementViewer.xaml, Tests/ViewModels/AchievementViewModelTests.cs
Closes #411 
Added as a link in the header to be similar to the Copy Title/Copy Description links in the leaderboard viewer.
=> add Copy Definition to Clipboard link in achievement viewer

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/ExpressionBase.cs, Source/Parser/Expressions/FloatConstantExpression.cs, Source/Parser/Functions/ArrayContainsFunction.cs, Source/Parser/Functions/DictionaryContainsKeyFunction.cs, Tests/Parser/Functions/ArrayContainsFunctionTests.cs, Tests/Parser/Functions/DictionaryContainsKeyFunctionTests.cs
`array_contains(array, value)` returns true/false depending on whether or not the provided value was found in the array. Effectively the same as `any_of(array, v => v == value)`.
`dictionary_contains_key(dictionary, key)` returns true/false depending on whether or not the provided key was found in the dictionary. Effectively the same as `any_of(dictionary, k => k == key)`.
While these functions are both wrappers for simple logical constructs that can already be created, there's very little need to actually have them, but they make the code a little bit easier to read. Additionally, they're slightly faster as the processing occurs natively instead of in the interpreter.
=> add array_contains and dictionary_contains_key functions

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/InterpreterScope.cs, Tests/Parser/Expressions/FunctionCallExpressionTests.cs
The logic to prevent functions from seeing variables defined in another function up the call stack was also preventing the logic from finding functions defined in another function up the call stack, which is necessary to be able to call a function recursively. I've modified the logic to look for function definitions at every point in the stack, but not variables.
=> fix recursively calling nested function

Source/Data/Value.cs, Source/Parser/RichPresenceBuilder.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs, Tests/Parser/ValueBuilderTests.cs
https://discord.com/channels/310192285306454017/1285315597843955773/1294128018834456627
Legacy syntax supports division by integer values, but not division by floating point values. The division must be inverted to a multiplication, or non-legacy syntax used.
=> don't generate legacy value syntax with division by float

Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Source/Parser/Expressions/Trigger/TalliedRequirementExpression.cs, Source/Parser/Functions/AlwaysFalseFunction.cs, Source/Parser/Functions/AlwaysTrueFunction.cs, Source/Parser/Functions/BitFunction.cs, Source/Parser/Functions/DisableWhenFunction.cs, Source/Parser/Functions/FlagConditionFunction.cs, Source/Parser/Functions/IdentityTransformFunction.cs, Source/Parser/Functions/MaxOfFunction.cs, Source/Parser/Functions/MeasuredFunction.cs, Source/Parser/Functions/MemoryAccessorFunction.cs, Source/Parser/Functions/OnceFunction.cs, Source/Parser/Functions/PrevPriorFunction.cs, Source/Parser/Functions/RangeFunction.cs, Source/Parser/Functions/RepeatedFunction.cs, Source/Parser/Functions/RichPresenceAsciiStringLookupFunction.cs, Source/Parser/Functions/RichPresenceLookupFunction.cs, Source/Parser/Functions/RichPresenceMacroFunction.cs, Source/Parser/Functions/RichPresenceValueFunction.cs, Source/Parser/Functions/TallyFunction.cs, Source/Parser/Functions/TallyOfFunction.cs, Tests/Parser/Expressions/Trigger/BehavioralRequirementExpression_Tests.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
closes #504
Causes the problematic subclause `never(repeated(N, once(A=1 && B=2) && (C=3 || D=4)))` to generate an error instead of being incorrectly interpolated.
The bulk of the modifications are calling a function overload when a function call fails so the line number is reported correctly.
=> generate error when repeated clause contains distinct AndNext and OrNext clauses

Source/Data/Requirement.cs, Source/Data/RequirementOperator.cs, Source/Parser/ScriptBuilderContext.cs, Tests/Data/RequirementTests.cs, Tests/ViewModels/RequirementComparisonViewModelTests.cs
As shown in https://github.com/Jamiras/RATools/issues/541#issuecomment-2477605343, the `^` was not being displayed in the achievement viewer.
=> fix display of xor operator in achievement display

Source/Data/RichPresence.cs
As discussed here: https://discord.com/channels/310192285306454017/310195377993416714/1308831251062329415
The 65535 limit is bytes, not characters. The UI limits the characters to 60000.
=> update rich presence length limit

Source/Parser/AchievementScriptInterpreter.cs, Source/Parser/Functions/AllOfFunction.cs, Source/Parser/Functions/AnyOfFunction.cs, Source/Parser/Functions/ArrayFilterFunction.cs, Source/Parser/Functions/ArrayMapFunction.cs, Source/Parser/Functions/ArrayReduceFunction.cs, Source/Parser/Functions/IterableJoiningFunction.cs, Source/Parser/Functions/NoneOfFunction.cs, Source/Parser/Functions/SumOfFunction.cs, Tests/Parser/Functions/ArrayFilterFunctionTests.cs, Tests/Parser/Functions/ArrayReduceFunctionTests.cs
Really feel these missing when working with any sort of functional paradigm in scripts. Adds both with test cases.
`array_filter` was added as an IterableJoiningFunction. Its base Evaluate method had to be updated to pass the predicate input into the Combine call, and I renamed the variables for clarity since "left" and "right" don't really apply in the general reducer case. This allows future predicate functions to do more general reducer things in their Evaluate functions.
Ironically though, the `array_reduce` function can't inherit that class since its signature is different (as is the signature of its reducer function). I spent some time trying to refactor IterableJoiningFunction to be more general so as to not repeat code, but ended up deciding that exposing the raw reduce …
=> Add array_filter and array_reduce functions

Source/Parser/Internal/RequirementMerger.cs, Source/Parser/Internal/RequirementsOptimizer.cs, Tests/Parser/Internal/RequirementMergerTests.cs, Tests/Parser/Internal/RequirementsOptimizerTests.cs
For example:
```
ResetIf a != 1
a != 5
```
If `a` is not 1, the achievement cannot possibly trigger because of the ResetIf, so `a` must be something other than 5 at the time it triggers, making the second clause unnecessary.
=> eliminate non-ResetIf conditions that are always true when ResetIf is not true

Source/ViewModels/GameViewModel.cs, Source/ViewModels/UpdateLocalViewModel.cs, Source/Views/UpdateLocalDialog.xaml
The tooltip shows the full path to the file, and clicking the link opens the explorer with the file selected.
=> add link to local file in Update Local dialog

Source/Data/Value.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs
fixes #558 
A rich presence macro containing a single expression was assumed to be a memref and a constant multiplier. Using a memref multiplier was unhandled, so it turned the address into a constant and proceeded.
=> fix legacy value serialization of combining two memrefs

Source/Parser/Expressions/IndexedVariableExpression.cs, Source/ViewModels/GameViewModel.cs, Tests/Parser/Expressions/FunctionCallExpressionTests.cs, Tests/Parser/Expressions/IndexedVariableExpressionTests.cs
fixes #560 
Parsing the logic was working fine. There was an issue trying to apply the syntax highlighting.
=> prevent null exception highlighting indexed function result

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Tests/Parser/Expressions/Trigger/MemoryValueExpressionTests.cs
fixes #561 
If the right side is already a `prev(pointer)` with a matching left side `(pointer)`, don't try to find a `(pointer)/prev(pointer)` pair on the left to split across the comparison.
=> fix infinite loop trying to rebalance SubSource prev comparison with multiple pointers

Source/Parser/Expressions/Trigger/RequirementClauseExpression.cs, Tests/Parser/Expressions/Trigger/BehavioralRequirementExpression_Tests.cs
Fixes https://discord.com/channels/310192285306454017/936655398725902356/1367192440666193920
Caused by two very similar conditions being wrapped in `unless()` incorrectly:
```
unless(String_Compare(Name(), Name1) &&
unless(String_Compare(Name(), Name2)))
```
instead of
```
unless(String_Compare(Name(), Name1)) &&
unless(String_Compare(Name(), Name2))
```
As a result, the second clause was being merged into the first clause, and due to the extreme similarity, it was trying to eliminate the same condition multiple times.
=> prevent IndexOutOfRangeException if multiple clauses of complex subclause can be eliminated

Source/Parser/Expressions/FunctionDefinitionExpression.cs, Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/Parser/Functions/BitFunction.cs, Source/Parser/Functions/MemoryAccessorFunction.cs, Tests/Parser/Functions/RichPresenceAsciiStringLookupFunctionTests.cs
Fixes #562.
The three functions that accept an address as a parameter (`rich_presence_ascii_string_lookup`, `ascii_string_equals` and `unicode_string_equals`) all use the same helper function to convert an address into a memory accessor. Since `dword(....)` is already a memory accessor, no conversion was being made, but the intent was to wrap it in another layer of `dword()`.
I've separated the logic that converts a memory value into a memory accessor from the logic that wraps a memory value in a memory accessor, and the affected functions will now always wrap the address parameter in a memory accessor.
=> fix reading memory at pointer address with no offset

Source/Data/Value.cs, Tests/Parser/Functions/RichPresenceValueFunctionTests.cs
fixes https://discord.com/channels/310192285306454017/936655398725902356/1352487987770032138
"Division by 1 billion" was being converted to "multiplication by 1E-09", then back to division as "division by 999999999.9999998" (or something similar). Since it wasn't an even integer value, the code chose to keep the multiplication and output 1E-09 to six significant digits, resulting in 0.000000, which was simplified to just 0.
Solution: track division separately instead of deriving it by inverting the multiplication accumulator.
=> track divisor separately to avoid rounding error

Source/Parser/ScriptBuilderContext.cs, Tests/Parser/Internal/ScriptBuilderContextTests.cs
fixes https://discord.com/channels/310192285306454017/936655398725902356/1373759776428785685
When dumping a clause containing a ResetNextIf and an OrNext, the OrNext was not being logically grouped with its neighbors so the thing being ORed got ANDed to the ResetNextIf.
=> add additional parenthesis when dumping clause with ResetNextIf and OrNext

Source/Parser/Expressions/Trigger/RequirementConditionExpression.cs, Source/Parser/Functions/PrevPriorFunction.cs, Tests/Parser/Expressions/Trigger/RequirementConditionExpression_Tests.cs
Addresses incorrect extraction of BCD from comparison with modification as described [here](https://github.com/Jamiras/RATools/issues/573#issuecomment-2891902564).
This does not attempt to convert `prev(bcd(X)) + n` into an `AddSource` chain of `high4`/`low4` memory reads, but that will now generate an error.
=> fix bcd extraction for modified memory read; report error when bcd cannot be extracted

Source/Parser/Expressions/Trigger/MemoryValueExpression.cs, Source/Parser/Expressions/Trigger/ModifiedMemoryAccessorExpression.cs, Source/Parser/Internal/TriggerBuilderContext.cs, Tests/Parser/AchievementScriptInterpreterTests.cs, Tests/Parser/Functions/AchievementFunctionTests.cs
Addresses https://discord.com/channels/310192285306454017/936655398725902356/1395832001218478161
Correctly reports when multiple unique Remembers exist in a single AddSource chain and eliminates redundant Remember when current Remembered value matches new Remembered value.
=> generate error when trying to use conflicting Remembers in AddSource chain
